using System.Security.Claims;
using System.Security.Cryptography;
using GymMaster.API.Data;
using GymMaster.API.DTOs;
using GymMaster.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.JsonWebTokens;

namespace GymMaster.API.Services;

public sealed class MemberService : IMemberService
{
    private const int DefaultPageSize = 20;
    private const int MaxPageSize = 100;

    private readonly GymMasterDbContext _dbContext;
    private readonly IAuditService _auditService;

    public MemberService(GymMasterDbContext dbContext, IAuditService auditService)
    {
        _dbContext = dbContext;
        _auditService = auditService;
    }

    // FR-MEM-01: tao MemberProfile + User role Member.
    public async Task<AuthServiceResult<CreateMemberResponse>> CreateAsync(
        CreateMemberRequest request,
        CancellationToken cancellationToken)
    {
        var email = NormalizeEmail(request.Email);
        var phone = NormalizePhone(request.Phone);

        if (string.IsNullOrWhiteSpace(request.FullName) || string.IsNullOrWhiteSpace(email))
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Vui long nhap ho ten va email.", StatusCodes.Status400BadRequest);
        }

        if (!IsValidEmail(email))
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Email khong hop le.", StatusCodes.Status400BadRequest);
        }

        if (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 6)
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Mat khau phai co it nhat 6 ky tu.", StatusCodes.Status400BadRequest);
        }

        // Neu email da ton tai: chi gan ho so vao tai khoan member da co, KHONG dung toi mat khau (bao mat).
        var existing = await _dbContext.Users
            .Include(item => item.UserRoles)
            .ThenInclude(item => item.Role)
            .FirstOrDefaultAsync(item => item.Email == email && !item.IsDeleted, cancellationToken);

        if (existing is not null)
        {
            if (!existing.UserRoles.Any(userRole => userRole.Role.Name == RoleNames.Member))
            {
                return Fail<CreateMemberResponse>(
                    "DUPLICATE", "Email nay da duoc dung boi mot tai khoan khac.", StatusCodes.Status409Conflict);
            }

            if (await _dbContext.MemberProfiles.AnyAsync(
                    item => item.UserId == existing.Id && !item.IsDeleted, cancellationToken))
            {
                return Fail<CreateMemberResponse>(
                    "DUPLICATE", "Hoi vien nay da co ho so.", StatusCodes.Status409Conflict);
            }

            var linkedProfile = BuildProfile(request);
            linkedProfile.UserId = existing.Id;
            linkedProfile.User = existing;
            _dbContext.MemberProfiles.Add(linkedProfile);
            await _dbContext.SaveChangesAsync(cancellationToken);

            await _auditService.LogAsync("CREATE_MEMBER", "MemberProfile", linkedProfile.Id, new { linked = true }, cancellationToken);

            return AuthServiceResult<CreateMemberResponse>.Success(
                new CreateMemberResponse(ToResponse(linkedProfile), null, false, true),
                StatusCodes.Status201Created);
        }

        if (phone is not null &&
            await _dbContext.Users.AnyAsync(user => user.Phone == phone && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateMemberResponse>("DUPLICATE", "So dien thoai nay da duoc su dung.", StatusCodes.Status409Conflict);
        }

        var memberRole = await GetRoleAsync(RoleNames.Member, cancellationToken);
        var autoGenerated = string.IsNullOrWhiteSpace(request.Password);
        var password = autoGenerated ? GenerateTemporaryPassword() : request.Password!;

        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = request.FullName.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(password, 12),
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = memberRole });

        var profile = BuildProfile(request);
        profile.User = user;

        _dbContext.Users.Add(user);
        _dbContext.MemberProfiles.Add(profile);
        await _dbContext.SaveChangesAsync(cancellationToken);

        // AC-06: AuditLog CREATE_MEMBER.
        await _auditService.LogAsync("CREATE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return AuthServiceResult<CreateMemberResponse>.Success(
            new CreateMemberResponse(ToResponse(profile), password, autoGenerated, false),
            StatusCodes.Status201Created);
    }

    // FR-MEM-02: tim kiem + phan trang.
    public async Task<AuthServiceResult<PagedResult<MemberResponse>>> ListAsync(
        string? query,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        page = page < 1 ? 1 : page;
        pageSize = pageSize is < 1 or > MaxPageSize ? DefaultPageSize : pageSize;

        var members = _dbContext.MemberProfiles
            .Include(profile => profile.User)
            .Where(profile => !profile.IsDeleted && !profile.User.IsDeleted);

        if (!string.IsNullOrWhiteSpace(query))
        {
            var keyword = query.Trim();
            members = members.Where(profile =>
                profile.User.FullName.Contains(keyword) ||
                profile.User.Email.Contains(keyword) ||
                (profile.User.Phone != null && profile.User.Phone.Contains(keyword)));
        }

        var total = await members.CountAsync(cancellationToken);
        var items = await members
            .OrderByDescending(profile => profile.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var totalPages = (int)Math.Ceiling(total / (double)pageSize);
        var result = new PagedResult<MemberResponse>(
            items.Select(ToResponse).ToList(), page, pageSize, total, totalPages);

        return AuthServiceResult<PagedResult<MemberResponse>>.Success(result);
    }

    // FR-MEM-05 / AC-04: Admin-Staff xem moi ho so; Member chi xem cua minh.
    public async Task<AuthServiceResult<MemberResponse>> GetByIdAsync(
        long id,
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<MemberResponse>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        if (!CanAccess(principal, profile))
        {
            return Fail<MemberResponse>("FORBIDDEN", "Ban khong co quyen xem ho so nay.", StatusCodes.Status403Forbidden);
        }

        return AuthServiceResult<MemberResponse>.Success(ToResponse(profile));
    }

    // Canonical Member 360 profile for Admin/Staff, assigned PT, and the member themself.
    public async Task<AuthServiceResult<Member360Response>> GetProfile360Async(
        long id,
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<Member360Response>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        var canAccess = await CanAccess360Async(principal, profile, cancellationToken);

        if (!canAccess)
        {
            return Fail<Member360Response>("FORBIDDEN", "Ban khong co quyen xem ho so nay.", StatusCodes.Status403Forbidden);
        }

        var currentMembership = await _dbContext.Memberships
            .Include(membership => membership.Package)
            .Where(membership =>
                membership.MemberId == id &&
                membership.Status != MembershipStatus.Cancelled)
            .OrderByDescending(membership => membership.Status == MembershipStatus.Active)
            .ThenByDescending(membership => membership.EndDate)
            .FirstOrDefaultAsync(cancellationToken);

        var activeAssignment = await _dbContext.TrainerAssignments
            .Include(assignment => assignment.Trainer)
            .ThenInclude(trainer => trainer.User)
            .Where(assignment => assignment.MemberId == id && assignment.Status == AssignmentStatuses.Active)
            .OrderByDescending(assignment => assignment.StartDate)
            .ThenByDescending(assignment => assignment.CreatedAt)
            .FirstOrDefaultAsync(cancellationToken);

        var recentCheckIns = await _dbContext.CheckIns
            .Where(checkIn => checkIn.MemberId == id)
            .OrderByDescending(checkIn => checkIn.CheckInAt)
            .Take(5)
            .Select(checkIn => new Member360CheckInResponse(checkIn.Id, checkIn.CheckInAt))
            .ToListAsync(cancellationToken);

        var response = new Member360Response(
            new Member360MemberResponse(
                profile.Id,
                $"MEM-{profile.Id:D6}",
                profile.User.FullName,
                profile.User.Email,
                profile.User.Phone,
                profile.User.Status),
            currentMembership is null
                ? null
                : new Member360MembershipResponse(
                    currentMembership.Id,
                    currentMembership.Package?.Name ?? $"Package #{currentMembership.PackageId}",
                    currentMembership.StartDate,
                    currentMembership.EndDate,
                    ToMembershipStatus(currentMembership.Status),
                    currentMembership.Status == MembershipStatus.Active ? "paid" : "pending"),
            activeAssignment is null
                ? null
                : new Member360AssignedPtResponse(
                    activeAssignment.TrainerId,
                    activeAssignment.Trainer?.User?.FullName ?? "Huấn luyện viên",
                    activeAssignment.Trainer?.Specialty,
                    activeAssignment.CreatedAt),
            recentCheckIns);

        return AuthServiceResult<Member360Response>.Success(response);
    }

    public async Task<AuthServiceResult<long>> GetCurrentMemberProfileIdAsync(
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var userId = GetActorId(principal);

        if (userId is null)
        {
            return Fail<long>("UNAUTHORIZED", "Khong xac dinh duoc danh tinh.", StatusCodes.Status401Unauthorized);
        }

        var memberId = await _dbContext.MemberProfiles
            .Where(profile => profile.UserId == userId && !profile.IsDeleted && !profile.User.IsDeleted)
            .Select(profile => profile.Id)
            .FirstOrDefaultAsync(cancellationToken);

        if (memberId == 0)
        {
            return Fail<long>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        return AuthServiceResult<long>.Success(memberId);
    }

    // FR-MEM-03: cap nhat ho so.
    public async Task<AuthServiceResult<MemberResponse>> UpdateAsync(
        long id,
        UpdateMemberRequest request,
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<MemberResponse>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        if (!CanAccess(principal, profile))
        {
            return Fail<MemberResponse>("FORBIDDEN", "Ban khong co quyen sua ho so nay.", StatusCodes.Status403Forbidden);
        }

        if (!string.IsNullOrWhiteSpace(request.FullName))
        {
            profile.User.FullName = request.FullName.Trim();
        }

        if (request.Phone is not null)
        {
            var phone = NormalizePhone(request.Phone);

            if (phone is not null && await _dbContext.Users.AnyAsync(
                    other => other.Phone == phone && other.Id != profile.UserId && !other.IsDeleted, cancellationToken))
            {
                return Fail<MemberResponse>("DUPLICATE", "So dien thoai nay da duoc su dung.", StatusCodes.Status409Conflict);
            }

            profile.User.Phone = phone;
        }

        if (request.DateOfBirth is not null)
        {
            profile.DateOfBirth = request.DateOfBirth;
        }

        if (request.Gender is not null)
        {
            profile.Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim();
        }

        if (request.Address is not null)
        {
            profile.Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim();
        }

        if (request.EmergencyContact is not null)
        {
            profile.EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim();
        }

        var now = DateTime.UtcNow;
        profile.UpdatedAt = now;
        profile.User.UpdatedAt = now;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return AuthServiceResult<MemberResponse>.Success(ToResponse(profile));
    }

    // FR-MEM-04 / DATA-01: soft-delete.
    public async Task<AuthServiceResult<object>> DeleteAsync(long id, CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<object>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        profile.IsDeleted = true;
        profile.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("DELETE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return AuthServiceResult<object>.Success(new { });
    }

    private Task<MemberProfile?> FindAsync(long id, CancellationToken cancellationToken)
    {
        return _dbContext.MemberProfiles
            .Include(profile => profile.User)
            .FirstOrDefaultAsync(profile => profile.Id == id && !profile.IsDeleted && !profile.User.IsDeleted, cancellationToken);
    }

    // Admin/Staff: moi ho so. Member: chi cua minh (ownership). PT: can spec 005 (assignment) -> tam 403.
    private static bool CanAccess(ClaimsPrincipal principal, MemberProfile profile)
    {
        if (principal.IsInRole(RoleNames.Admin) || principal.IsInRole(RoleNames.Staff))
        {
            return true;
        }

        if (principal.IsInRole(RoleNames.Member))
        {
            return GetActorId(principal) == profile.UserId;
        }

        return false;
    }

    private async Task<bool> CanAccess360Async(
        ClaimsPrincipal principal,
        MemberProfile profile,
        CancellationToken cancellationToken)
    {
        if (principal.IsInRole(RoleNames.Admin) || principal.IsInRole(RoleNames.Staff))
        {
            return true;
        }

        var actorId = GetActorId(principal);

        if (actorId is null)
        {
            return false;
        }

        if (principal.IsInRole(RoleNames.Member))
        {
            return actorId == profile.UserId;
        }

        if (!principal.IsInRole(RoleNames.Pt))
        {
            return false;
        }

        var trainerProfile = await _dbContext.TrainerProfiles
            .FirstOrDefaultAsync(
                trainer => trainer.UserId == actorId && !trainer.IsDeleted,
                cancellationToken);

        if (trainerProfile is null)
        {
            return false;
        }

        return await _dbContext.TrainerAssignments.AnyAsync(
            assignment =>
                assignment.MemberId == profile.Id &&
                assignment.TrainerId == trainerProfile.Id &&
                assignment.Status == AssignmentStatuses.Active,
            cancellationToken);
    }

    private async Task<Role> GetRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        var role = await _dbContext.Roles.FirstOrDefaultAsync(item => item.Name == roleName, cancellationToken);

        if (role is not null)
        {
            return role;
        }

        role = new Role { Name = roleName, Description = $"{roleName} role" };
        _dbContext.Roles.Add(role);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return role;
    }

    private static MemberProfile BuildProfile(CreateMemberRequest request)
    {
        return new MemberProfile
        {
            DateOfBirth = request.DateOfBirth,
            Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim(),
            Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim(),
            EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim(),
            JoinedAt = DateTime.UtcNow
        };
    }

    private static MemberResponse ToResponse(MemberProfile profile)
    {
        return new MemberResponse(
            profile.Id,
            profile.UserId,
            $"MEM-{profile.Id:D6}",
            profile.User.Email,
            profile.User.FullName,
            profile.User.Phone,
            profile.DateOfBirth,
            profile.Gender,
            profile.Address,
            profile.EmergencyContact,
            profile.JoinedAt,
            profile.User.Status,
            profile.CreatedAt);
    }

    private static string ToMembershipStatus(MembershipStatus status)
    {
        return status switch
        {
            MembershipStatus.Active => "active",
            MembershipStatus.PendingPayment => "pending_payment",
            MembershipStatus.Expired => "expired",
            MembershipStatus.Cancelled => "cancelled",
            _ => "expired"
        };
    }

    private static long? GetActorId(ClaimsPrincipal principal)
    {
        var value = principal.FindFirstValue(ClaimTypes.NameIdentifier) ??
            principal.FindFirstValue(JwtRegisteredClaimNames.Sub);

        return long.TryParse(value, out var userId) ? userId : null;
    }

    private static string GenerateTemporaryPassword()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(9));
    }

    private static bool IsValidEmail(string email)
    {
        var at = email.IndexOf('@');
        return at > 0 && at < email.Length - 1;
    }

    private static string NormalizeEmail(string? email)
    {
        return email?.Trim().ToLowerInvariant() ?? string.Empty;
    }

    private static string? NormalizePhone(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone) ? null : phone.Trim();
    }

    private static AuthServiceResult<T> Fail<T>(string code, string message, int statusCode)
    {
        return AuthServiceResult<T>.Failure(code, message, statusCode);
    }
}
