using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using GymMaster.API.Data;
using GymMaster.API.DTOs;
using GymMaster.API.Entities;
using Microsoft.EntityFrameworkCore;

namespace GymMaster.API.Services;

public sealed class TrainerService : ITrainerService
{
    private const int DefaultPageSize = 20;
    private const int MaxPageSize = 100;

    private readonly GymMasterDbContext _dbContext;
    private readonly IAuditService _auditService;

    public TrainerService(GymMasterDbContext dbContext, IAuditService auditService)
    {
        _dbContext = dbContext;
        _auditService = auditService;
    }

    // FR-PT-PROF-01: tao TrainerProfile gan voi User role PT.
    public async Task<AuthServiceResult<CreateTrainerResponse>> CreateAsync(
        CreateTrainerRequest request,
        CancellationToken cancellationToken)
    {
        if (request.UserId is null)
        {
            return await CreateWithAccountAsync(request, cancellationToken);
        }

        var user = await _dbContext.Users
            .Include(item => item.UserRoles)
            .ThenInclude(item => item.Role)
            .FirstOrDefaultAsync(item => item.Id == request.UserId.Value && !item.IsDeleted, cancellationToken);

        if (user is null)
        {
            return Fail<CreateTrainerResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        if (!user.UserRoles.Any(userRole => userRole.Role.Name == RoleNames.Pt))
        {
            return Fail<CreateTrainerResponse>(
                "INVALID_ROLE",
                "Nguoi dung nay khong phai role PT.",
                StatusCodes.Status422UnprocessableEntity);
        }

        if (await _dbContext.TrainerProfiles.AnyAsync(
                profile => profile.UserId == user.Id && !profile.IsDeleted, cancellationToken))
        {
            return Fail<CreateTrainerResponse>("DUPLICATE", "Nguoi dung nay da co ho so PT.", StatusCodes.Status409Conflict);
        }

        if (request.YearsOfExperience is < 0)
        {
            return Fail<CreateTrainerResponse>(
                "VALIDATION_ERROR", "So nam kinh nghiem khong hop le.", StatusCodes.Status400BadRequest);
        }

        var profile = BuildProfile(request);
        profile.UserId = user.Id;
        profile.User = user;

        _dbContext.TrainerProfiles.Add(profile);
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("CREATE_TRAINER", "TrainerProfile", profile.Id, null, cancellationToken);

        return AuthServiceResult<CreateTrainerResponse>.Success(
            new CreateTrainerResponse(ToResponse(profile), null, false, true),
            StatusCodes.Status201Created);
    }

    private async Task<AuthServiceResult<CreateTrainerResponse>> CreateWithAccountAsync(
        CreateTrainerRequest request,
        CancellationToken cancellationToken)
    {
        var email = NormalizeEmail(request.Email);
        var phone = NormalizePhone(request.Phone);

        if (string.IsNullOrWhiteSpace(request.FullName) || string.IsNullOrWhiteSpace(email))
        {
            return Fail<CreateTrainerResponse>(
                "VALIDATION_ERROR", "Vui long nhap ho ten va email.", StatusCodes.Status400BadRequest);
        }

        if (!IsValidEmail(email))
        {
            return Fail<CreateTrainerResponse>(
                "VALIDATION_ERROR", "Email khong hop le.", StatusCodes.Status400BadRequest);
        }

        if (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 6)
        {
            return Fail<CreateTrainerResponse>(
                "VALIDATION_ERROR", "Mat khau phai co it nhat 6 ky tu.", StatusCodes.Status400BadRequest);
        }

        if (request.YearsOfExperience is < 0)
        {
            return Fail<CreateTrainerResponse>(
                "VALIDATION_ERROR", "So nam kinh nghiem khong hop le.", StatusCodes.Status400BadRequest);
        }

        if (await _dbContext.Users.AnyAsync(user => user.Email == email && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateTrainerResponse>(
                "DUPLICATE",
                "Email nay da duoc su dung. Neu muon gan ho so PT cho tai khoan co san, dung truong UserId.",
                StatusCodes.Status409Conflict);
        }

        if (phone is not null &&
            await _dbContext.Users.AnyAsync(user => user.Phone == phone && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateTrainerResponse>("DUPLICATE", "So dien thoai nay da duoc su dung.", StatusCodes.Status409Conflict);
        }

        var ptRole = await GetRoleAsync(RoleNames.Pt, cancellationToken);
        var autoGenerated = string.IsNullOrWhiteSpace(request.Password);
        var password = autoGenerated ? GenerateTemporaryPassword() : request.Password!;

        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = request.FullName.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(password, 12),
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = ptRole });

        var profile = BuildProfile(request);
        profile.User = user;

        _dbContext.Users.Add(user);
        _dbContext.TrainerProfiles.Add(profile);
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync(
            "CREATE_TRAINER",
            "TrainerProfile",
            profile.Id,
            new { accountCreated = true },
            cancellationToken);

        return AuthServiceResult<CreateTrainerResponse>.Success(
            new CreateTrainerResponse(ToResponse(profile), password, autoGenerated, false),
            StatusCodes.Status201Created);
    }

    public async Task<AuthServiceResult<PagedResult<TrainerResponse>>> ListAsync(
        string? query,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        page = page < 1 ? 1 : page;
        pageSize = pageSize is < 1 or > MaxPageSize ? DefaultPageSize : pageSize;

        var trainers = _dbContext.TrainerProfiles
            .Include(profile => profile.User)
            .Where(profile => !profile.IsDeleted && !profile.User.IsDeleted);

        if (!string.IsNullOrWhiteSpace(query))
        {
            var keyword = query.Trim();
            trainers = trainers.Where(profile =>
                profile.User.FullName.Contains(keyword) ||
                profile.User.Email.Contains(keyword) ||
                (profile.Specialty != null && profile.Specialty.Contains(keyword)));
        }

        var total = await trainers.CountAsync(cancellationToken);
        var items = await trainers
            .OrderByDescending(profile => profile.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var totalPages = (int)Math.Ceiling(total / (double)pageSize);
        var result = new PagedResult<TrainerResponse>(
            items.Select(ToResponse).ToList(), page, pageSize, total, totalPages);

        return AuthServiceResult<PagedResult<TrainerResponse>>.Success(result);
    }

    public async Task<AuthServiceResult<TrainerResponse>> GetByIdAsync(long id, CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        return profile is null
            ? Fail<TrainerResponse>("NOT_FOUND", "Khong tim thay ho so PT.", StatusCodes.Status404NotFound)
            : AuthServiceResult<TrainerResponse>.Success(ToResponse(profile));
    }

    public async Task<AuthServiceResult<TrainerResponse>> GetCurrentAsync(
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var userId = GetActorId(principal);

        if (userId is null)
        {
            return Fail<TrainerResponse>("UNAUTHORIZED", "Khong xac dinh duoc danh tinh.", StatusCodes.Status401Unauthorized);
        }

        var profile = await _dbContext.TrainerProfiles
            .Include(item => item.User)
            .FirstOrDefaultAsync(
                item => item.UserId == userId.Value && !item.IsDeleted && !item.User.IsDeleted,
                cancellationToken);

        return profile is null
            ? Fail<TrainerResponse>("NOT_FOUND", "Khong tim thay ho so huan luyen vien.", StatusCodes.Status404NotFound)
            : AuthServiceResult<TrainerResponse>.Success(ToResponse(profile));
    }

    public async Task<AuthServiceResult<TrainerResponse>> UpdateAsync(
        long id,
        UpdateTrainerRequest request,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<TrainerResponse>("NOT_FOUND", "Khong tim thay ho so PT.", StatusCodes.Status404NotFound);
        }

        if (request.Specialty is not null)
        {
            profile.Specialty = string.IsNullOrWhiteSpace(request.Specialty) ? null : request.Specialty.Trim();
        }

        if (request.Bio is not null)
        {
            profile.Bio = string.IsNullOrWhiteSpace(request.Bio) ? null : request.Bio.Trim();
        }

        if (request.Gender is not null)
        {
            profile.Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim();
        }

        if (request.DateOfBirth is not null)
        {
            profile.DateOfBirth = request.DateOfBirth;
        }

        if (request.Address is not null)
        {
            profile.Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim();
        }

        if (request.EmergencyContact is not null)
        {
            profile.EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim();
        }

        if (request.YearsOfExperience is not null)
        {
            if (request.YearsOfExperience < 0)
            {
                return Fail<TrainerResponse>(
                    "VALIDATION_ERROR", "So nam kinh nghiem khong hop le.", StatusCodes.Status400BadRequest);
            }

            profile.YearsOfExperience = request.YearsOfExperience;
        }

        profile.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_TRAINER", "TrainerProfile", profile.Id, null, cancellationToken);

        return AuthServiceResult<TrainerResponse>.Success(ToResponse(profile));
    }

    private Task<TrainerProfile?> FindAsync(long id, CancellationToken cancellationToken)
    {
        return _dbContext.TrainerProfiles
            .Include(profile => profile.User)
            .FirstOrDefaultAsync(profile => profile.Id == id && !profile.IsDeleted && !profile.User.IsDeleted, cancellationToken);
    }

    private async Task<Role> GetRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        var role = await _dbContext.Roles.FirstOrDefaultAsync(item => item.Name == roleName, cancellationToken);

        if (role is not null)
        {
            return role;
        }

        role = new Role { Name = roleName, Description = $"{roleName} role" };
        _dbContext.Roles.Add(role);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return role;
    }

    private static TrainerProfile BuildProfile(CreateTrainerRequest request)
    {
        return new TrainerProfile
        {
            Specialty = string.IsNullOrWhiteSpace(request.Specialty) ? null : request.Specialty.Trim(),
            Bio = string.IsNullOrWhiteSpace(request.Bio) ? null : request.Bio.Trim(),
            Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim(),
            DateOfBirth = request.DateOfBirth,
            Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim(),
            EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim(),
            YearsOfExperience = request.YearsOfExperience
        };
    }

    private static TrainerResponse ToResponse(TrainerProfile profile)
    {
        return new TrainerResponse(
            profile.Id,
            profile.UserId,
            profile.User.Email,
            profile.User.FullName,
            profile.User.Status,
            profile.Specialty,
            profile.Bio,
            profile.Gender,
            profile.DateOfBirth,
            profile.Address,
            profile.EmergencyContact,
            profile.YearsOfExperience,
            profile.CreatedAt);
    }

    private static long? GetActorId(ClaimsPrincipal principal)
    {
        var value = principal.FindFirstValue(ClaimTypes.NameIdentifier) ??
            principal.FindFirstValue(JwtRegisteredClaimNames.Sub);

        return long.TryParse(value, out var userId) ? userId : null;
    }

    private static string GenerateTemporaryPassword()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(9));
    }

    private static bool IsValidEmail(string email)
    {
        var at = email.IndexOf('@');
        return at > 0 && at < email.Length - 1;
    }

    private static string NormalizeEmail(string? email)
    {
        return email?.Trim().ToLowerInvariant() ?? string.Empty;
    }

    private static string? NormalizePhone(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone) ? null : phone.Trim();
    }

    private static AuthServiceResult<T> Fail<T>(string code, string message, int statusCode)
    {
        return AuthServiceResult<T>.Failure(code, message, statusCode);
    }
}
