using System.Security.Cryptography;
using GymMaster.API.Data;
using GymMaster.API.DTOs;
using GymMaster.API.Entities;
using Microsoft.EntityFrameworkCore;

namespace GymMaster.API.Services;

public sealed class UserService : IUserService
{
    private const int DefaultPageSize = 20;
    private const int MaxPageSize = 100;

    private readonly GymMasterDbContext _dbContext;
    private readonly IAuditService _auditService;

    public UserService(GymMasterDbContext dbContext, IAuditService auditService)
    {
        _dbContext = dbContext;
        _auditService = auditService;
    }

    // FR-USR-01: Admin tao tai khoan voi role chi dinh, trang thai Active.
    public async Task<AuthServiceResult<CreateUserResponse>> CreateAsync(
        CreateUserRequest request,
        CancellationToken cancellationToken)
    {
        var email = NormalizeEmail(request.Email);
        var phone = NormalizePhone(request.Phone);
        var role = NormalizeRole(request.Role);

        if (string.IsNullOrWhiteSpace(request.FullName) || string.IsNullOrWhiteSpace(email))
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Vui long nhap ho ten va email.",
                StatusCodes.Status400BadRequest);
        }

        if (!IsValidEmail(email))
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Email khong hop le.",
                StatusCodes.Status400BadRequest);
        }

        if (role is null)
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Role khong hop le (admin/staff/pt/member).",
                StatusCodes.Status400BadRequest);
        }

        // Admin co the tu nhap mat khau; de trong -> he thong tu sinh mat khau tam.
        if (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 6)
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Mat khau phai co it nhat 6 ky tu.",
                StatusCodes.Status400BadRequest);
        }

        // FR-USR-02: email/phone da ton tai -> 409.
        if (await _dbContext.Users.AnyAsync(user => user.Email == email && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateUserResponse>(
                "DUPLICATE",
                "Email nay da duoc su dung.",
                StatusCodes.Status409Conflict);
        }

        if (phone is not null &&
            await _dbContext.Users.AnyAsync(user => user.Phone == phone && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateUserResponse>(
                "DUPLICATE",
                "So dien thoai nay da duoc su dung.",
                StatusCodes.Status409Conflict);
        }

        var roleEntity = await GetRoleAsync(role, cancellationToken);
        var autoGenerated = string.IsNullOrWhiteSpace(request.Password);
        var password = autoGenerated ? GenerateTemporaryPassword() : request.Password!;

        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = request.FullName.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(password, 12),
            Status = UserStatuses.Active
        };

        user.UserRoles.Add(new UserRole { User = user, Role = roleEntity });
        _dbContext.Users.Add(user);
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("CREATE_USER", "User", user.Id, new { role }, cancellationToken);

        return AuthServiceResult<CreateUserResponse>.Success(
            new CreateUserResponse(ToResponse(user), password, autoGenerated),
            StatusCodes.Status201Created);
    }

    // FR-MEM-02: tim kiem theo ten/email/SDT (khong phan biet hoa thuong) + phan trang.
    public async Task<AuthServiceResult<PagedResult<AdminUserResponse>>> ListAsync(
        string? query,
        string? role,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        page = page < 1 ? 1 : page;
        pageSize = pageSize is < 1 or > MaxPageSize ? DefaultPageSize : pageSize;

        var users = _dbContext.Users
            .Include(user => user.UserRoles)
            .ThenInclude(userRole => userRole.Role)
            .Where(user => !user.IsDeleted);

        if (!string.IsNullOrWhiteSpace(query))
        {
            var keyword = query.Trim();
            users = users.Where(user =>
                user.FullName.Contains(keyword) ||
                user.Email.Contains(keyword) ||
                (user.Phone != null && user.Phone.Contains(keyword)));
        }

        var roleFilter = NormalizeRole(role);
        if (roleFilter is not null)
        {
            users = users.Where(user => user.UserRoles.Any(userRole => userRole.Role.Name == roleFilter));
        }

        var totalItems = await users.CountAsync(cancellationToken);
        var items = await users
            .OrderByDescending(user => user.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize);
        var result = new PagedResult<AdminUserResponse>(
            items.Select(ToResponse).ToList(),
            page,
            pageSize,
            totalItems,
            totalPages);

        return AuthServiceResult<PagedResult<AdminUserResponse>>.Success(result);
    }

    public async Task<AuthServiceResult<AdminUserResponse>> GetByIdAsync(
        long id,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        return user is null
            ? Fail<AdminUserResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound)
            : AuthServiceResult<AdminUserResponse>.Success(ToResponse(user));
    }

    // FR-MEM-03: validate va luu, cap nhat UpdatedAt.
    public async Task<AuthServiceResult<AdminUserResponse>> UpdateAsync(
        long id,
        UpdateUserRequest request,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<AdminUserResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        if (!string.IsNullOrWhiteSpace(request.FullName))
        {
            user.FullName = request.FullName.Trim();
        }

        if (request.Phone is not null)
        {
            var phone = NormalizePhone(request.Phone);

            if (phone is not null && await _dbContext.Users.AnyAsync(
                    other => other.Phone == phone && other.Id != id && !other.IsDeleted, cancellationToken))
            {
                return Fail<AdminUserResponse>(
                    "DUPLICATE",
                    "So dien thoai nay da duoc su dung.",
                    StatusCodes.Status409Conflict);
            }

            user.Phone = phone;
        }

        if (!string.IsNullOrWhiteSpace(request.Status))
        {
            var status = request.Status.Trim().ToLowerInvariant();

            if (status != UserStatuses.Active && status != UserStatuses.Locked)
            {
                return Fail<AdminUserResponse>(
                    "VALIDATION_ERROR",
                    "Status khong hop le (active/locked).",
                    StatusCodes.Status400BadRequest);
            }

            user.Status = status;
        }

        if (!string.IsNullOrWhiteSpace(request.Role))
        {
            var role = NormalizeRole(request.Role);

            if (role is null)
            {
                return Fail<AdminUserResponse>(
                    "VALIDATION_ERROR",
                    "Role khong hop le (admin/staff/pt/member).",
                    StatusCodes.Status400BadRequest);
            }

            var roleEntity = await GetRoleAsync(role, cancellationToken);
            user.UserRoles.Clear();
            user.UserRoles.Add(new UserRole { User = user, Role = roleEntity });
        }

        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_USER", "User", user.Id, null, cancellationToken);

        return AuthServiceResult<AdminUserResponse>.Success(ToResponse(user));
    }

    // FR-MEM-04 / DATA-01: soft-delete, KHONG xoa cung.
    public async Task<AuthServiceResult<object>> DeleteAsync(
        long id,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<object>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        user.IsDeleted = true;
        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("DELETE_USER", "User", user.Id, null, cancellationToken);

        return AuthServiceResult<object>.Success(new { });
    }

    private Task<User?> FindAsync(long id, CancellationToken cancellationToken)
    {
        return _dbContext.Users
            .Include(user => user.UserRoles)
            .ThenInclude(userRole => userRole.Role)
            .FirstOrDefaultAsync(user => user.Id == id && !user.IsDeleted, cancellationToken);
    }

    private async Task<Role> GetRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        var role = await _dbContext.Roles.FirstOrDefaultAsync(item => item.Name == roleName, cancellationToken);

        if (role is not null)
        {
            return role;
        }

        role = new Role { Name = roleName, Description = $"{roleName} role" };
        _dbContext.Roles.Add(role);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return role;
    }

    private static AdminUserResponse ToResponse(User user)
    {
        return new AdminUserResponse(
            user.Id,
            user.Email,
            user.FullName,
            user.Phone,
            user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member,
            user.Status,
            user.LastLoginAt,
            user.CreatedAt);
    }

    private static string GenerateTemporaryPassword()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(9));
    }

    private static bool IsValidEmail(string email)
    {
        var at = email.IndexOf('@');
        return at > 0 && at < email.Length - 1;
    }

    private static string NormalizeEmail(string? email)
    {
        return email?.Trim().ToLowerInvariant() ?? string.Empty;
    }

    private static string? NormalizePhone(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone) ? null : phone.Trim();
    }

    private static string? NormalizeRole(string? role)
    {
        if (string.IsNullOrWhiteSpace(role))
        {
            return null;
        }

        var normalized = role.Trim().ToLowerInvariant();
        return RoleNames.All.Contains(normalized) ? normalized : null;
    }

    private static AuthServiceResult<T> Fail<T>(string code, string message, int statusCode)
    {
        return AuthServiceResult<T>.Failure(code, message, statusCode);
    }
}
