using System.Security.Claims;
using GymMaster.API.Common;
using GymMaster.API.Data;
using GymMaster.API.Entities;
using GymMaster.API.Features.Dashboard;
using GymMaster.API.Features.Members;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace GymMaster.Api.Tests;

// Spec 002 — trong tam la CreateAsync voi BA nhanh email khac nhau, cong voi
// GetOrCreateCurrentProfileAsync (GET co side-effect, AC-08) va soft delete (AC-05).
public class MemberServiceTests
{
    private static GymMasterDbContext NewDb()
    {
        var options = new DbContextOptionsBuilder<GymMasterDbContext>()
            .UseInMemoryDatabase($"member-{Guid.NewGuid()}")
            .Options;
        return new GymMasterDbContext(options);
    }

    private static MemberService NewService(GymMasterDbContext db, IAuditService? audit = null)
        => new(db, audit ?? new NoopAudit());

    private static async Task<Role> SeedMemberRoleAsync(GymMasterDbContext db)
    {
        var role = new Role { Id = 4, Name = RoleNames.Member };
        db.Roles.Add(role);
        await db.SaveChangesAsync();
        return role;
    }

    private static async Task<User> SeedUserAsync(
        GymMasterDbContext db, string email, Role role, string? phone = null)
    {
        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = "Nguoi Dung",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword("matkhau123", 12),
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = role });
        db.Users.Add(user);
        await db.SaveChangesAsync();
        return user;
    }

    private static CreateMemberRequest Request(string email, string? password = null, string? phone = null)
        => new("Nguyen Van A", email, phone, password, null, null, null, null);

    private static ClaimsPrincipal MemberPrincipal(long userId)
        => new(new ClaimsIdentity(
            new[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Role, RoleNames.Member)
            }, "test"));

    // ---------- Nhanh 1: email CHUA ton tai -> tao ca User + MemberProfile ----------

    [Fact]
    public async Task Create_with_a_new_email_creates_both_user_and_profile()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);

        var result = await NewService(db).CreateAsync(Request("moi@gym.test"), default);

        Assert.True(result.Succeeded);
        Assert.Equal(StatusCodes.Status201Created, result.StatusCode);
        Assert.False(result.Value!.LinkedToExistingAccount);

        Assert.Equal(1, await db.Users.CountAsync(item => item.Email == "moi@gym.test"));
        Assert.Equal(1, await db.MemberProfiles.CountAsync());
    }

    [Fact]
    public async Task Create_without_password_generates_a_temporary_one_and_returns_it_once()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);

        var result = await NewService(db).CreateAsync(Request("moi@gym.test"), default);

        Assert.True(result.Value!.PasswordAutoGenerated);
        Assert.False(string.IsNullOrWhiteSpace(result.Value.InitialPassword));

        // Mat khau tra ve phai la mat khau that dang nhap duoc (da hash trong DB).
        var user = await db.Users.FirstAsync();
        Assert.True(BCrypt.Net.BCrypt.Verify(result.Value.InitialPassword!, user.PasswordHash));
    }

    [Fact]
    public async Task Create_with_a_supplied_password_does_not_flag_auto_generated()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);

        var result = await NewService(db).CreateAsync(Request("moi@gym.test", password: "matkhau123"), default);

        Assert.False(result.Value!.PasswordAutoGenerated);
        var user = await db.Users.FirstAsync();
        Assert.True(BCrypt.Net.BCrypt.Verify("matkhau123", user.PasswordHash));
    }

    // ---------- Nhanh 2: email la Member CHUA co ho so -> chi gan ho so ----------

    [Fact]
    public async Task Create_links_a_profile_onto_an_existing_member_account_without_touching_the_password()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        var existing = await SeedUserAsync(db, "dangky@gym.test", role);
        var hashBefore = existing.PasswordHash;

        var result = await NewService(db).CreateAsync(Request("dangky@gym.test", password: "matkhaukhac"), default);

        Assert.True(result.Succeeded);
        Assert.True(result.Value!.LinkedToExistingAccount);
        Assert.Null(result.Value.InitialPassword);

        // Khong tao them User, va TUYET DOI khong doi mat khau cua tai khoan da co.
        Assert.Equal(1, await db.Users.CountAsync());
        var after = await db.Users.FirstAsync(item => item.Id == existing.Id);
        Assert.Equal(hashBefore, after.PasswordHash);
    }

    // ---------- Nhanh 3: da co ho so, hoac email thuoc role khac -> 409 ----------

    [Fact]
    public async Task Create_refuses_when_the_member_already_has_a_profile()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        await SeedUserAsync(db, "dangky@gym.test", role);
        await NewService(db).CreateAsync(Request("dangky@gym.test"), default);

        var second = await NewService(db).CreateAsync(Request("dangky@gym.test"), default);

        Assert.False(second.Succeeded);
        Assert.Equal("DUPLICATE", second.ErrorCode);
        Assert.Equal(StatusCodes.Status409Conflict, second.StatusCode);
    }

    [Fact]
    public async Task Create_refuses_when_the_email_belongs_to_another_role()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);
        var staffRole = new Role { Id = 2, Name = RoleNames.Staff };
        db.Roles.Add(staffRole);
        await db.SaveChangesAsync();
        await SeedUserAsync(db, "nhanvien@gym.test", staffRole);

        var result = await NewService(db).CreateAsync(Request("nhanvien@gym.test"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
    }

    [Fact]
    public async Task Create_refuses_a_phone_already_used_by_someone_else()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        await SeedUserAsync(db, "cu@gym.test", role, phone: "0900000001");

        var result = await NewService(db).CreateAsync(
            Request("moi@gym.test", phone: "0900000001"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
    }

    // ---------- Validate dau vao ----------

    [Fact]
    public async Task Create_rejects_an_invalid_email()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);

        var result = await NewService(db).CreateAsync(Request("khong-phai-email"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
        Assert.Equal(StatusCodes.Status400BadRequest, result.StatusCode);
    }

    [Fact]
    public async Task Create_rejects_a_password_shorter_than_six_characters()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);

        var result = await NewService(db).CreateAsync(Request("moi@gym.test", password: "123"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    // ---------- AC-08: GET /members/me tu tao ho so neu chua co ----------

    [Fact]
    public async Task GetOrCreateCurrentProfile_creates_the_profile_when_the_member_has_none()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        var user = await SeedUserAsync(db, "dangky@gym.test", role);

        Assert.Equal(0, await db.MemberProfiles.CountAsync());

        var result = await NewService(db).GetOrCreateCurrentProfileAsync(MemberPrincipal(user.Id), default);

        Assert.True(result.Succeeded);
        Assert.Equal(1, await db.MemberProfiles.CountAsync());
    }

    [Fact]
    public async Task GetOrCreateCurrentProfile_is_stable_when_called_twice()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        var user = await SeedUserAsync(db, "dangky@gym.test", role);
        var service = NewService(db);

        var first = await service.GetOrCreateCurrentProfileAsync(MemberPrincipal(user.Id), default);
        var second = await service.GetOrCreateCurrentProfileAsync(MemberPrincipal(user.Id), default);

        Assert.Equal(first.Value, second.Value);
        Assert.Equal(1, await db.MemberProfiles.CountAsync());
    }

    [Fact]
    public async Task GetOrCreateCurrentProfile_restores_a_soft_deleted_profile_in_place()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);
        var audit = new RecordingAudit();
        var service = NewService(db, audit);
        var created = await service.CreateAsync(Request("moi@gym.test"), default);
        var originalId = created.Value!.Member.Id;
        var userId = created.Value.Member.UserId;
        await service.DeleteAsync(originalId, default);

        var restored = await service.GetOrCreateCurrentProfileAsync(MemberPrincipal(userId), default);

        Assert.True(restored.Succeeded);
        Assert.Equal(originalId, restored.Value);
        Assert.Equal(1, await db.MemberProfiles.CountAsync());
        Assert.False((await db.MemberProfiles.SingleAsync()).IsDeleted);
        Assert.Contains(audit.Entries, entry =>
            entry.Action == "RESTORE_MEMBER" &&
            entry.Entity == "MemberProfile" &&
            entry.EntityId == originalId);
    }

    [Fact]
    public async Task Create_restores_a_soft_deleted_profile_and_preserves_related_history()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);
        var audit = new RecordingAudit();
        var service = NewService(db, audit);
        var created = await service.CreateAsync(Request("moi@gym.test"), default);
        var originalId = created.Value!.Member.Id;
        var originalProfile = await db.MemberProfiles.AsNoTracking().SingleAsync();
        db.ProgressLogs.Add(new ProgressLog
        {
            MemberId = originalId,
            MeasuredAt = DateTime.UtcNow,
            WeightKg = 70
        });
        await db.SaveChangesAsync();
        await service.DeleteAsync(originalId, default);

        var restored = await service.CreateAsync(
            new CreateMemberRequest(
                "Nguyen Van A",
                "moi@gym.test",
                null,
                null,
                new DateTime(2000, 1, 2),
                "Male",
                "Ha Noi",
                "0900000000"),
            default);

        Assert.True(restored.Succeeded);
        Assert.True(restored.Value!.LinkedToExistingAccount);
        Assert.Equal(originalId, restored.Value.Member.Id);
        Assert.Equal(1, await db.MemberProfiles.CountAsync());
        Assert.Equal(originalId, (await db.ProgressLogs.SingleAsync()).MemberId);

        var profile = await db.MemberProfiles.SingleAsync();
        Assert.False(profile.IsDeleted);
        Assert.Equal(originalProfile.JoinedAt, profile.JoinedAt);
        Assert.Equal(originalProfile.CreatedAt, profile.CreatedAt);
        Assert.Equal(new DateTime(2000, 1, 2), profile.DateOfBirth);
        Assert.Equal("Ha Noi", profile.Address);
        Assert.Contains(audit.Entries, entry =>
            entry.Action == "RESTORE_MEMBER" &&
            entry.Entity == "MemberProfile" &&
            entry.EntityId == originalId);
    }

    // ---------- AC-05: soft delete, khong xoa cung ----------

    [Fact]
    public async Task Delete_only_flags_the_profile_and_keeps_the_row()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);
        var created = await NewService(db).CreateAsync(Request("moi@gym.test"), default);
        var id = created.Value!.Member.Id;

        var deleted = await NewService(db).DeleteAsync(id, default);
        Assert.True(deleted.Succeeded);

        // Ban ghi VAN CON trong DB (DATA-01) nhung bi danh dau da xoa.
        var row = await db.MemberProfiles.IgnoreQueryFilters().FirstAsync(item => item.Id == id);
        Assert.True(row.IsDeleted);
    }

    [Fact]
    public async Task List_does_not_return_soft_deleted_members()
    {
        using var db = NewDb();
        await SeedMemberRoleAsync(db);
        var service = NewService(db);
        var created = await service.CreateAsync(Request("moi@gym.test"), default);
        await service.DeleteAsync(created.Value!.Member.Id, default);

        var list = await service.ListAsync(null, 1, 20, default);

        Assert.True(list.Succeeded);
        Assert.Empty(list.Value!.Items);
    }

    // ---------- AC-04: Member khong xem duoc ho so nguoi khac ----------

    [Fact]
    public async Task Member_cannot_read_another_members_profile()
    {
        using var db = NewDb();
        var role = await SeedMemberRoleAsync(db);
        var service = NewService(db);
        var other = await service.CreateAsync(Request("nguoikhac@gym.test"), default);
        var intruder = await SeedUserAsync(db, "toi@gym.test", role);

        var result = await service.GetByIdAsync(
            other.Value!.Member.Id, MemberPrincipal(intruder.Id), default);

        Assert.False(result.Succeeded);
        Assert.Equal(StatusCodes.Status403Forbidden, result.StatusCode);
    }

    private sealed class NoopAudit : IAuditService
    {
        public Task LogAsync(string action, string entity, long entityId, object? metadata, CancellationToken cancellationToken)
            => Task.CompletedTask;
    }

    private sealed class RecordingAudit : IAuditService
    {
        public List<(string Action, string Entity, long EntityId)> Entries { get; } = new();

        public Task LogAsync(
            string action,
            string entity,
            long entityId,
            object? metadata,
            CancellationToken cancellationToken)
        {
            Entries.Add((action, entity, entityId));
            return Task.CompletedTask;
        }
    }
}
