using System.Security.Claims;
using GymMaster.API.Data;
using GymMaster.API.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using GymMaster.API.Features.Dashboard;
using GymMaster.API.Features.Trainers;

namespace GymMaster.Api.Tests;

public class TrainerServiceTests
{
    private static GymMasterDbContext NewDb()
    {
        var options = new DbContextOptionsBuilder<GymMasterDbContext>()
            .UseInMemoryDatabase($"gym-{Guid.NewGuid()}")
            .Options;
        return new GymMasterDbContext(options);
    }

    private static ClaimsPrincipal Pt(long userId)
    {
        var identity = new ClaimsIdentity(
            new[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Role, RoleNames.Pt),
            },
            "test");
        return new ClaimsPrincipal(identity);
    }

    private static TrainerService NewService(GymMasterDbContext db)
        => new(db, new NoopAudit());

    [Fact]
    public async Task GetCurrent_returns_own_trainer_profile_for_pt()
    {
        using var db = NewDb();
        var user = new User
        {
            Id = 20,
            Email = "pt@gymmaster.local",
            FullName = "GymMaster PT",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        };
        db.Users.Add(user);
        db.TrainerProfiles.Add(new TrainerProfile
        {
            Id = 7,
            UserId = user.Id,
            Specialty = "Strength",
            Bio = "Coach bio",
            YearsOfExperience = 5,
            IsDeleted = false
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).GetCurrentAsync(Pt(user.Id), default);

        Assert.True(result.Succeeded);
        Assert.Equal(7, result.Value!.Id);
        Assert.Equal(user.Id, result.Value.UserId);
        Assert.Equal("pt@gymmaster.local", result.Value.Email);
        Assert.Equal("Strength", result.Value.Specialty);
    }

    [Fact]
    public async Task GetCurrent_returns_not_found_when_pt_has_no_profile()
    {
        using var db = NewDb();
        db.Users.Add(new User
        {
            Id = 21,
            Email = "pt2@gymmaster.local",
            FullName = "GymMaster PT 2",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).GetCurrentAsync(Pt(21), default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
        Assert.Equal("Khong tim thay ho so huan luyen vien.", result.ErrorMessage);
        Assert.Equal(StatusCodes.Status404NotFound, result.StatusCode);
    }

    [Fact]
    public async Task Create_one_step_creates_user_role_and_profile_with_generated_password()
    {
        using var db = NewDb();
        var service = NewService(db);

        var result = await service.CreateAsync(
            new CreateTrainerRequest(
                " Nguyen Coach ",
                "COACH@GYMMASTER.LOCAL",
                " 0909000000 ",
                null,
                " Strength ",
                " Coach bio ",
                " Male ",
                null,
                4),
            default);

        Assert.True(result.Succeeded);
        Assert.NotNull(result.Value!.InitialPassword);
        Assert.True(result.Value.PasswordAutoGenerated);
        Assert.Equal("coach@gymmaster.local", result.Value.Trainer.Email);
        Assert.Equal("Nguyen Coach", result.Value.Trainer.FullName);
        Assert.Equal("Strength", result.Value.Trainer.Specialty);

        var user = await db.Users
            .Include(item => item.UserRoles)
            .ThenInclude(item => item.Role)
            .SingleAsync();
        Assert.Equal("coach@gymmaster.local", user.Email);
        Assert.Equal("0909000000", user.Phone);
        Assert.Contains(user.UserRoles, item => item.Role.Name == RoleNames.Pt);
        Assert.True(await db.TrainerProfiles.AnyAsync(item => item.UserId == user.Id));
    }

    [Fact]
    public async Task Create_one_step_uses_explicit_password()
    {
        using var db = NewDb();
        var service = NewService(db);

        var result = await service.CreateAsync(
            new CreateTrainerRequest(
                "Coach Password",
                "coach.password@gymmaster.local",
                null,
                "secret1",
                null,
                null,
                null,
                null,
                null),
            default);

        Assert.True(result.Succeeded);
        Assert.Equal("secret1", result.Value!.InitialPassword);
        Assert.False(result.Value.PasswordAutoGenerated);
    }

    [Fact]
    public async Task Create_one_step_rejects_existing_email()
    {
        using var db = NewDb();
        db.Users.Add(new User
        {
            Email = "used@gymmaster.local",
            FullName = "Used",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).CreateAsync(
            new CreateTrainerRequest(
                "Coach Used",
                " USED@GYMMASTER.LOCAL ",
                null,
                null,
                null,
                null,
                null,
                null,
                null),
            default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
        Assert.Equal(StatusCodes.Status409Conflict, result.StatusCode);
    }

    [Fact]
    public async Task Create_requires_name_and_email()
    {
        using var db = NewDb();

        var result = await NewService(db).CreateAsync(
            new CreateTrainerRequest(null, null, null, null, "Strength", null, null, null, null),
            default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
        Assert.Equal(StatusCodes.Status400BadRequest, result.StatusCode);
    }

    [Fact]
    public async Task Contact_fields_roundtrip_through_create_and_update()
    {
        using var db = NewDb();
        var service = NewService(db);

        var created = await service.CreateAsync(
            new CreateTrainerRequest(
                "Contact Coach",
                "contact.coach@gymmaster.local",
                null,
                null,
                "Mobility",
                null,
                null,
                null,
                null,
                " 123 Coach Street ",
                " 0900111222 "),
            default);

        Assert.True(created.Succeeded);
        Assert.Equal("123 Coach Street", created.Value!.Trainer.Address);
        Assert.Equal("0900111222", created.Value.Trainer.EmergencyContact);

        var updated = await service.UpdateAsync(
            created.Value.Trainer.Id,
            new UpdateTrainerRequest(null, null, null, null, null, " ", " 0900333444 "),
            default);

        Assert.True(updated.Succeeded);
        Assert.Null(updated.Value!.Address);
        Assert.Equal("0900333444", updated.Value.EmergencyContact);
    }

    private sealed class NoopAudit : IAuditService
    {
        public Task LogAsync(string action, string entity, long entityId, object? metadata, CancellationToken ct)
            => Task.CompletedTask;
    }
}
