using System.Security.Claims;
using GymMaster.API.Data;
using GymMaster.API.DTOs;
using GymMaster.API.Entities;
using GymMaster.API.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace GymMaster.Api.Tests;

public class TrainerServiceTests
{
    private static GymMasterDbContext NewDb()
    {
        var options = new DbContextOptionsBuilder<GymMasterDbContext>()
            .UseInMemoryDatabase($"gym-{Guid.NewGuid()}")
            .Options;
        return new GymMasterDbContext(options);
    }

    private static ClaimsPrincipal Pt(long userId)
    {
        var identity = new ClaimsIdentity(
            new[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Role, RoleNames.Pt),
            },
            "test");
        return new ClaimsPrincipal(identity);
    }

    private static TrainerService NewService(GymMasterDbContext db)
        => new(db, new NoopAudit());

    private static async Task<Role> SeedRoleAsync(GymMasterDbContext db, string roleName)
    {
        var role = new Role { Name = roleName, Description = $"{roleName} role" };
        db.Roles.Add(role);
        await db.SaveChangesAsync();
        return role;
    }

    [Fact]
    public async Task GetCurrent_returns_own_trainer_profile_for_pt()
    {
        using var db = NewDb();
        var user = new User
        {
            Id = 20,
            Email = "pt@gymmaster.local",
            FullName = "GymMaster PT",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        };
        db.Users.Add(user);
        db.TrainerProfiles.Add(new TrainerProfile
        {
            Id = 7,
            UserId = user.Id,
            Specialty = "Strength",
            Bio = "Coach bio",
            YearsOfExperience = 5,
            IsDeleted = false
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).GetCurrentAsync(Pt(user.Id), default);

        Assert.True(result.Succeeded);
        Assert.Equal(7, result.Value!.Id);
        Assert.Equal(user.Id, result.Value.UserId);
        Assert.Equal("pt@gymmaster.local", result.Value.Email);
        Assert.Equal("Strength", result.Value.Specialty);
    }

    [Fact]
    public async Task GetCurrent_returns_not_found_when_pt_has_no_profile()
    {
        using var db = NewDb();
        db.Users.Add(new User
        {
            Id = 21,
            Email = "pt2@gymmaster.local",
            FullName = "GymMaster PT 2",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).GetCurrentAsync(Pt(21), default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
        Assert.Equal("Khong tim thay ho so huan luyen vien.", result.ErrorMessage);
        Assert.Equal(StatusCodes.Status404NotFound, result.StatusCode);
    }

    [Fact]
    public async Task Create_one_step_creates_user_role_and_profile_with_generated_password()
    {
        using var db = NewDb();
        var service = NewService(db);

        var result = await service.CreateAsync(
            new CreateTrainerRequest(
                null,
                " Nguyen Coach ",
                "COACH@GYMMASTER.LOCAL",
                " 0909000000 ",
                null,
                " Strength ",
                " Coach bio ",
                " Male ",
                null,
                4),
            default);

        Assert.True(result.Succeeded);
        Assert.NotNull(result.Value!.InitialPassword);
        Assert.True(result.Value.PasswordAutoGenerated);
        Assert.False(result.Value.LinkedToExistingAccount);
        Assert.Equal("coach@gymmaster.local", result.Value.Trainer.Email);
        Assert.Equal("Nguyen Coach", result.Value.Trainer.FullName);
        Assert.Equal("Strength", result.Value.Trainer.Specialty);

        var user = await db.Users
            .Include(item => item.UserRoles)
            .ThenInclude(item => item.Role)
            .SingleAsync();
        Assert.Equal("coach@gymmaster.local", user.Email);
        Assert.Equal("0909000000", user.Phone);
        Assert.Contains(user.UserRoles, item => item.Role.Name == RoleNames.Pt);
        Assert.True(await db.TrainerProfiles.AnyAsync(item => item.UserId == user.Id));
    }

    [Fact]
    public async Task Create_one_step_uses_explicit_password()
    {
        using var db = NewDb();
        var service = NewService(db);

        var result = await service.CreateAsync(
            new CreateTrainerRequest(
                null,
                "Coach Password",
                "coach.password@gymmaster.local",
                null,
                "secret1",
                null,
                null,
                null,
                null,
                null),
            default);

        Assert.True(result.Succeeded);
        Assert.Equal("secret1", result.Value!.InitialPassword);
        Assert.False(result.Value.PasswordAutoGenerated);
        Assert.False(result.Value.LinkedToExistingAccount);
    }

    [Fact]
    public async Task Create_one_step_rejects_existing_email()
    {
        using var db = NewDb();
        db.Users.Add(new User
        {
            Email = "used@gymmaster.local",
            FullName = "Used",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        });
        await db.SaveChangesAsync();

        var result = await NewService(db).CreateAsync(
            new CreateTrainerRequest(
                null,
                "Coach Used",
                " USED@GYMMASTER.LOCAL ",
                null,
                null,
                null,
                null,
                null,
                null,
                null),
            default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
        Assert.Equal(StatusCodes.Status409Conflict, result.StatusCode);
    }

    [Fact]
    public async Task Create_legacy_user_id_links_existing_pt_account()
    {
        using var db = NewDb();
        var role = await SeedRoleAsync(db, RoleNames.Pt);
        var user = new User
        {
            Id = 30,
            Email = "legacy.pt@gymmaster.local",
            FullName = "Legacy PT",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = role });
        db.Users.Add(user);
        await db.SaveChangesAsync();

        var result = await NewService(db).CreateAsync(
            new CreateTrainerRequest(user.Id, null, null, null, null, "Mobility", null, null, null, 2),
            default);

        Assert.True(result.Succeeded);
        Assert.Null(result.Value!.InitialPassword);
        Assert.False(result.Value.PasswordAutoGenerated);
        Assert.True(result.Value.LinkedToExistingAccount);
        Assert.Equal(user.Id, result.Value.Trainer.UserId);
        Assert.Equal("Mobility", result.Value.Trainer.Specialty);
    }

    [Fact]
    public async Task Create_legacy_user_id_still_rejects_non_pt_user()
    {
        using var db = NewDb();
        var role = await SeedRoleAsync(db, RoleNames.Member);
        var user = new User
        {
            Id = 31,
            Email = "member@gymmaster.local",
            FullName = "Member",
            PasswordHash = "hash",
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = role });
        db.Users.Add(user);
        await db.SaveChangesAsync();

        var result = await NewService(db).CreateAsync(
            new CreateTrainerRequest(user.Id, null, null, null, null, null, null, null, null, null),
            default);

        Assert.False(result.Succeeded);
        Assert.Equal("INVALID_ROLE", result.ErrorCode);
        Assert.Equal(StatusCodes.Status422UnprocessableEntity, result.StatusCode);
    }

    private sealed class NoopAudit : IAuditService
    {
        public Task LogAsync(string action, string entity, long entityId, object? metadata, CancellationToken ct)
            => Task.CompletedTask;
    }
}
