using GymMaster.API.Data;
using GymMaster.API.Entities;
using GymMaster.API.Features.Dashboard;
using GymMaster.API.Features.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace GymMaster.Api.Tests;

// Bo sung coverage cho UserService: Create/List/GetById/UpdateStatus/ResetPassword/Delete.
public class UserServiceCoverageTests
{
    private static GymMasterDbContext NewDb()
    {
        var options = new DbContextOptionsBuilder<GymMasterDbContext>()
            .UseInMemoryDatabase($"gym-usercov-{Guid.NewGuid()}")
            .Options;
        return new GymMasterDbContext(options);
    }

    private sealed class NoopAudit : IAuditService
    {
        public Task LogAsync(string action, string entity, long entityId, object? metadata, CancellationToken ct)
            => Task.CompletedTask;
    }

    private static UserService NewService(GymMasterDbContext db) => new(db, new NoopAudit());

    private static CreateUserRequest Req(
        string fullName = "Nguyen Van A",
        string email = "a@gymmaster.local",
        string? phone = "0900000001",
        string role = RoleNames.Staff,
        string? password = null,
        DateTime? dob = null,
        string? gender = null,
        string? address = null,
        string? emergency = null)
        => new(fullName, email, phone, role, password, dob, gender, address, emergency);

    // ---------- CreateAsync ----------

    [Fact] // Happy path: khong nhap mat khau -> tu sinh, 201, hash BCrypt
    public async Task Create_autogenerates_password_and_returns_201()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(), default);

        Assert.True(result.Succeeded);
        Assert.Equal(StatusCodes.Status201Created, result.StatusCode);
        Assert.True(result.Value!.PasswordAutoGenerated);
        Assert.False(string.IsNullOrEmpty(result.Value.InitialPassword));

        var user = await db.Users.SingleAsync();
        Assert.Equal("a@gymmaster.local", user.Email);
        Assert.NotEqual("a@gymmaster.local", user.PasswordHash);
        Assert.True(BCrypt.Net.BCrypt.Verify(result.Value.InitialPassword, user.PasswordHash));
    }

    [Fact] // Admin tu nhap mat khau -> autoGenerated=false
    public async Task Create_with_password_is_not_autogenerated()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(password: "secret123"), default);

        Assert.True(result.Succeeded);
        Assert.False(result.Value!.PasswordAutoGenerated);
    }

    [Fact] // Email/normalize: chu HOA + khoang trang -> luu thuong, trim
    public async Task Create_normalizes_email_lowercase_trim()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(email: "  MiXeD@Gym.Local "), default);

        Assert.True(result.Succeeded);
        Assert.Equal("mixed@gym.local", (await db.Users.SingleAsync()).Email);
    }

    [Theory] // Thieu ten / thieu email -> VALIDATION_ERROR 400
    [InlineData("", "a@gym.local")]
    [InlineData("Ten", "")]
    public async Task Create_missing_required_fields_returns_validation_error(string name, string email)
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(fullName: name, email: email), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
        Assert.Equal(StatusCodes.Status400BadRequest, result.StatusCode);
    }

    [Theory] // Email khong hop le
    [InlineData("nodomain")]
    [InlineData("@gym.local")]
    [InlineData("trailing@")]
    public async Task Create_invalid_email_returns_validation_error(string email)
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(email: email), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    [Fact] // Role khong hop le
    public async Task Create_invalid_role_returns_validation_error()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(role: "superuser"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    [Fact] // Mat khau < 6 ky tu
    public async Task Create_short_password_returns_validation_error()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(password: "123"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    [Fact] // PersonValidation: ho ten qua dai
    public async Task Create_person_validation_error_when_name_too_long()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(Req(fullName: new string('x', 200)), default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    [Fact] // Trung email -> DUPLICATE 409
    public async Task Create_duplicate_email_returns_conflict()
    {
        using var db = NewDb();
        await NewService(db).CreateAsync(Req(email: "dup@gym.local", phone: "0900000001"), default);

        var result = await NewService(db).CreateAsync(Req(email: "dup@gym.local", phone: "0900000002"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
        Assert.Equal(StatusCodes.Status409Conflict, result.StatusCode);
    }

    [Fact] // Trung SDT -> DUPLICATE 409
    public async Task Create_duplicate_phone_returns_conflict()
    {
        using var db = NewDb();
        await NewService(db).CreateAsync(Req(email: "one@gym.local", phone: "0900000009"), default);

        var result = await NewService(db).CreateAsync(Req(email: "two@gym.local", phone: "0900000009"), default);

        Assert.False(result.Succeeded);
        Assert.Equal("DUPLICATE", result.ErrorCode);
    }

    [Fact] // Staff kem thong tin ca nhan -> tao StaffProfile
    public async Task Create_staff_with_personal_fields_creates_staff_profile()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(
            Req(role: RoleNames.Staff, dob: new DateTime(1995, 1, 1), gender: "male", address: "1 Ly Thuong Kiet", emergency: "0900000000"),
            default);

        Assert.True(result.Succeeded);
        var profile = await db.StaffProfiles.SingleAsync();
        Assert.Equal("1 Ly Thuong Kiet", profile.Address);
        Assert.Equal("male", profile.Gender);
    }

    [Fact] // Member kem thong tin ca nhan -> KHONG tao StaffProfile (chi admin/staff)
    public async Task Create_member_with_personal_fields_does_not_create_staff_profile()
    {
        using var db = NewDb();
        var result = await NewService(db).CreateAsync(
            Req(role: RoleNames.Member, address: "Nha rieng"),
            default);

        Assert.True(result.Succeeded);
        Assert.False(await db.StaffProfiles.AnyAsync());
    }

    // ---------- ListAsync ----------

    [Fact] // Filter theo query + role + phan trang
    public async Task List_filters_by_query_and_role_and_paginates()
    {
        using var db = NewDb();
        var svc = NewService(db);
        await svc.CreateAsync(Req(fullName: "Alpha Staff", email: "alpha@gym.local", phone: "0900000010", role: RoleNames.Staff), default);
        await svc.CreateAsync(Req(fullName: "Beta Staff", email: "beta@gym.local", phone: "0900000011", role: RoleNames.Staff), default);
        await svc.CreateAsync(Req(fullName: "Alpha Member", email: "am@gym.local", phone: "0900000012", role: RoleNames.Member), default);

        var byRole = await svc.ListAsync(null, RoleNames.Staff, 1, 10, default);
        Assert.True(byRole.Succeeded);
        Assert.Equal(2, byRole.Value!.Total);

        var byQuery = await svc.ListAsync("Alpha", null, 1, 10, default);
        Assert.Equal(2, byQuery.Value!.Total);

        var combined = await svc.ListAsync("Alpha", RoleNames.Member, 1, 10, default);
        Assert.Equal(1, combined.Value!.Total);
    }

    [Fact] // page/pageSize < 1 hoac qua lon -> ve default, khong crash
    public async Task List_normalizes_invalid_paging()
    {
        using var db = NewDb();
        await NewService(db).CreateAsync(Req(email: "x@gym.local"), default);

        var result = await NewService(db).ListAsync(null, null, 0, 9999, default);

        Assert.True(result.Succeeded);
        Assert.Equal(1, result.Value!.Page);
        Assert.Equal(20, result.Value.PageSize);
    }

    // ---------- GetByIdAsync ----------

    [Fact]
    public async Task GetById_returns_user_when_found()
    {
        using var db = NewDb();
        var created = await NewService(db).CreateAsync(Req(email: "get@gym.local"), default);

        var result = await NewService(db).GetByIdAsync(created.Value!.UserId, default);

        Assert.True(result.Succeeded);
        Assert.Equal("get@gym.local", result.Value!.Email);
    }

    [Fact]
    public async Task GetById_not_found()
    {
        using var db = NewDb();
        var result = await NewService(db).GetByIdAsync(999, default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
        Assert.Equal(StatusCodes.Status404NotFound, result.StatusCode);
    }

    // ---------- UpdateStatusAsync ----------

    [Theory]
    [InlineData(UserStatuses.Locked)]
    [InlineData(UserStatuses.Active)]
    public async Task UpdateStatus_valid_values(string status)
    {
        using var db = NewDb();
        var created = await NewService(db).CreateAsync(Req(email: "st@gym.local"), default);

        var result = await NewService(db).UpdateStatusAsync(created.Value!.UserId, $" {status.ToUpperInvariant()} ", default);

        Assert.True(result.Succeeded);
        Assert.Equal(status, result.Value!.Status);
    }

    [Fact]
    public async Task UpdateStatus_invalid_value_returns_validation_error()
    {
        using var db = NewDb();
        var created = await NewService(db).CreateAsync(Req(email: "st2@gym.local"), default);

        var result = await NewService(db).UpdateStatusAsync(created.Value!.UserId, "frozen", default);

        Assert.False(result.Succeeded);
        Assert.Equal("VALIDATION_ERROR", result.ErrorCode);
    }

    [Fact]
    public async Task UpdateStatus_not_found()
    {
        using var db = NewDb();
        var result = await NewService(db).UpdateStatusAsync(123, UserStatuses.Active, default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
    }

    // ---------- ResetPasswordAsync ----------

    [Fact]
    public async Task ResetPassword_returns_temp_and_changes_hash()
    {
        using var db = NewDb();
        var created = await NewService(db).CreateAsync(Req(email: "rp@gym.local", password: "original1"), default);
        var oldHash = (await db.Users.SingleAsync()).PasswordHash;

        var result = await NewService(db).ResetPasswordAsync(created.Value!.UserId, default);

        Assert.True(result.Succeeded);
        Assert.False(string.IsNullOrEmpty(result.Value!.TemporaryPassword));
        var newHash = (await db.Users.SingleAsync()).PasswordHash;
        Assert.NotEqual(oldHash, newHash);
        Assert.True(BCrypt.Net.BCrypt.Verify(result.Value.TemporaryPassword, newHash));
    }

    [Fact]
    public async Task ResetPassword_not_found()
    {
        using var db = NewDb();
        var result = await NewService(db).ResetPasswordAsync(42, default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
    }

    // ---------- DeleteAsync (soft-delete) ----------

    [Fact]
    public async Task Delete_soft_deletes_user()
    {
        using var db = NewDb();
        var created = await NewService(db).CreateAsync(Req(email: "del@gym.local"), default);

        var result = await NewService(db).DeleteAsync(created.Value!.UserId, default);

        Assert.True(result.Succeeded);
        Assert.True((await db.Users.SingleAsync()).IsDeleted);
        // Sau khi soft-delete: GetById khong con thay
        var afterGet = await NewService(db).GetByIdAsync(created.Value.UserId, default);
        Assert.False(afterGet.Succeeded);
    }

    [Fact]
    public async Task Delete_not_found()
    {
        using var db = NewDb();
        var result = await NewService(db).DeleteAsync(7, default);

        Assert.False(result.Succeeded);
        Assert.Equal("NOT_FOUND", result.ErrorCode);
    }
}
