namespace GymMaster.API.Features.Members;
// Spec 002 — Member profile (FR-MEM-01..05)

public sealed record CreateMemberRequest(
    string FullName,
    string Email,
    string? Phone,
    string? Password,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact);

public sealed record UpdateMemberRequest(
    string? FullName,
    string? Phone,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact);

public sealed record MemberResponse(
    long Id,
    long UserId,
    string MemberCode,
    string Email,
    string FullName,
    string? AvatarUrl,
    string? Phone,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact,
    DateTime JoinedAt,
    string Status,
    DateTime CreatedAt);

public sealed record CreateMemberResponse(
    MemberResponse Member,
    string? InitialPassword,
    bool PasswordAutoGenerated,
    bool LinkedToExistingAccount);
