using System.Security.Claims;
using System.Security.Cryptography;
using GymMaster.API.Data;
using GymMaster.API.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.JsonWebTokens;
using GymMaster.API.Common;
using GymMaster.API.Features.Dashboard;

namespace GymMaster.API.Features.Members;
public sealed class MemberService : IMemberService
{
    private const int DefaultPageSize = 20;
    private const int MaxPageSize = 100;

    private readonly GymMasterDbContext _dbContext;
    private readonly IAuditService _auditService;

    public MemberService(GymMasterDbContext dbContext, IAuditService auditService)
    {
        _dbContext = dbContext;
        _auditService = auditService;
    }

    // FR-MEM-01: tao MemberProfile + User role Member.
    public async Task<ServiceResult<CreateMemberResponse>> CreateAsync(
        CreateMemberRequest request,
        CancellationToken cancellationToken)
    {
        var email = NormalizeEmail(request.Email);
        var phone = NormalizePhone(request.Phone);

        if (string.IsNullOrWhiteSpace(request.FullName) || string.IsNullOrWhiteSpace(email))
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Vui long nhap ho ten va email.", StatusCodes.Status400BadRequest);
        }

        if (!IsValidEmail(email))
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Email khong hop le.", StatusCodes.Status400BadRequest);
        }

        if (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 6)
        {
            return Fail<CreateMemberResponse>(
                "VALIDATION_ERROR", "Mat khau phai co it nhat 6 ky tu.", StatusCodes.Status400BadRequest);
        }

        var personError = PersonValidation.Validate(
            fullName: request.FullName,
            phone: request.Phone,
            dateOfBirth: request.DateOfBirth,
            gender: request.Gender,
            address: request.Address,
            emergencyContact: request.EmergencyContact);
        if (personError is not null)
        {
            return Fail<CreateMemberResponse>("VALIDATION_ERROR", personError, StatusCodes.Status400BadRequest);
        }

        // Neu email da ton tai: chi gan ho so vao tai khoan member da co, KHONG dung toi mat khau (bao mat).
        var existing = await _dbContext.Users
            .Include(item => item.UserRoles)
            .ThenInclude(item => item.Role)
            .FirstOrDefaultAsync(item => item.Email == email && !item.IsDeleted, cancellationToken);

        if (existing is not null)
        {
            if (!existing.UserRoles.Any(userRole => userRole.Role.Name == RoleNames.Member))
            {
                return Fail<CreateMemberResponse>(
                    "DUPLICATE", "Email nay da duoc dung boi mot tai khoan khac.", StatusCodes.Status409Conflict);
            }

            if (await _dbContext.MemberProfiles.AnyAsync(
                    item => item.UserId == existing.Id && !item.IsDeleted, cancellationToken))
            {
                return Fail<CreateMemberResponse>(
                    "DUPLICATE", "Hoi vien nay da co ho so.", StatusCodes.Status409Conflict);
            }

            var linkedProfile = BuildProfile(request);
            linkedProfile.UserId = existing.Id;
            linkedProfile.User = existing;
            _dbContext.MemberProfiles.Add(linkedProfile);
            await _dbContext.SaveChangesAsync(cancellationToken);

            await _auditService.LogAsync("CREATE_MEMBER", "MemberProfile", linkedProfile.Id, new { linked = true }, cancellationToken);

            return ServiceResult<CreateMemberResponse>.Success(
                new CreateMemberResponse(ToResponse(linkedProfile), null, false, true),
                StatusCodes.Status201Created);
        }

        if (phone is not null &&
            await _dbContext.Users.AnyAsync(user => user.Phone == phone && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateMemberResponse>("DUPLICATE", "So dien thoai nay da duoc su dung.", StatusCodes.Status409Conflict);
        }

        var memberRole = await GetRoleAsync(RoleNames.Member, cancellationToken);
        var autoGenerated = string.IsNullOrWhiteSpace(request.Password);
        var password = autoGenerated ? GenerateTemporaryPassword() : request.Password!;

        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = request.FullName.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(password, 12),
            Status = UserStatuses.Active
        };
        user.UserRoles.Add(new UserRole { User = user, Role = memberRole });

        var profile = BuildProfile(request);
        profile.User = user;

        _dbContext.Users.Add(user);
        _dbContext.MemberProfiles.Add(profile);
        await _dbContext.SaveChangesAsync(cancellationToken);

        // AC-06: AuditLog CREATE_MEMBER.
        await _auditService.LogAsync("CREATE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return ServiceResult<CreateMemberResponse>.Success(
            new CreateMemberResponse(ToResponse(profile), password, autoGenerated, false),
            StatusCodes.Status201Created);
    }

    // FR-MEM-02: tim kiem + phan trang.
    public async Task<ServiceResult<PagedResult<MemberResponse>>> ListAsync(
        string? query,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        page = page < 1 ? 1 : page;
        pageSize = pageSize is < 1 or > MaxPageSize ? DefaultPageSize : pageSize;

        var members = _dbContext.MemberProfiles
            .Include(profile => profile.User)
            .Where(profile => !profile.IsDeleted && !profile.User.IsDeleted);

        if (!string.IsNullOrWhiteSpace(query))
        {
            var keyword = query.Trim();
            members = members.Where(profile =>
                profile.User.FullName.Contains(keyword) ||
                profile.User.Email.Contains(keyword) ||
                (profile.User.Phone != null && profile.User.Phone.Contains(keyword)));
        }

        var total = await members.CountAsync(cancellationToken);
        var items = await members
            .OrderByDescending(profile => profile.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var totalPages = (int)Math.Ceiling(total / (double)pageSize);
        var result = new PagedResult<MemberResponse>(
            items.Select(ToResponse).ToList(), page, pageSize, total, totalPages);

        return ServiceResult<PagedResult<MemberResponse>>.Success(result);
    }

    // FR-MEM-05 / AC-04: Admin-Staff xem moi ho so; Member chi xem cua minh.
    public async Task<ServiceResult<MemberResponse>> GetByIdAsync(
        long id,
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<MemberResponse>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        if (!CanAccess(principal, profile))
        {
            return Fail<MemberResponse>("FORBIDDEN", "Ban khong co quyen xem ho so nay.", StatusCodes.Status403Forbidden);
        }

        return ServiceResult<MemberResponse>.Success(ToResponse(profile));
    }

    public async Task<ServiceResult<long>> GetCurrentMemberProfileIdAsync(
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var userId = GetActorId(principal);

        if (userId is null)
        {
            return Fail<long>("UNAUTHORIZED", "Khong xac dinh duoc danh tinh.", StatusCodes.Status401Unauthorized);
        }

        var memberId = await _dbContext.MemberProfiles
            .Where(profile => profile.UserId == userId && !profile.IsDeleted && !profile.User.IsDeleted)
            .Select(profile => profile.Id)
            .FirstOrDefaultAsync(cancellationToken);

        if (memberId == 0)
        {
            return Fail<long>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        return ServiceResult<long>.Success(memberId);
    }

    public async Task<ServiceResult<long>> GetOrCreateCurrentProfileAsync(
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var userId = GetActorId(principal);

        if (userId is null)
        {
            return Fail<long>("UNAUTHORIZED", "Khong xac dinh duoc danh tinh.", StatusCodes.Status401Unauthorized);
        }

        var memberId = await FindCurrentProfileIdAsync(userId.Value, cancellationToken);
        if (memberId != 0)
        {
            return ServiceResult<long>.Success(memberId);
        }

        if (!principal.IsInRole(RoleNames.Member))
        {
            return Fail<long>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        var user = await _dbContext.Users.FirstOrDefaultAsync(
            item => item.Id == userId.Value && !item.IsDeleted, cancellationToken);

        if (user is null)
        {
            return Fail<long>("NOT_FOUND", "Khong tim thay tai khoan.", StatusCodes.Status404NotFound);
        }

        // Tu phuc vu: user role member chua co ho so -> tao ho so khi can quyen co ban.
        var profile = new MemberProfile
        {
            UserId = user.Id,
            User = user,
            JoinedAt = DateTime.UtcNow
        };

        _dbContext.MemberProfiles.Add(profile);

        try
        {
            await _dbContext.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException exception) when (IsMemberProfileUserUniqueViolation(exception))
        {
            _dbContext.Entry(profile).State = EntityState.Detached;

            memberId = await FindCurrentProfileIdAsync(userId.Value, cancellationToken);
            if (memberId != 0)
            {
                return ServiceResult<long>.Success(memberId);
            }

            throw;
        }

        await _auditService.LogAsync("CREATE_MEMBER", "MemberProfile", profile.Id, new { selfService = true }, cancellationToken);

        return ServiceResult<long>.Success(profile.Id);
    }

    // FR-MEM-03: cap nhat ho so.
    public async Task<ServiceResult<MemberResponse>> UpdateAsync(
        long id,
        UpdateMemberRequest request,
        ClaimsPrincipal principal,
        CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<MemberResponse>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        if (!CanAccess(principal, profile))
        {
            return Fail<MemberResponse>("FORBIDDEN", "Ban khong co quyen sua ho so nay.", StatusCodes.Status403Forbidden);
        }

        var personError = PersonValidation.Validate(
            fullName: request.FullName,
            phone: request.Phone,
            dateOfBirth: request.DateOfBirth,
            gender: request.Gender,
            address: request.Address,
            emergencyContact: request.EmergencyContact);
        if (personError is not null)
        {
            return Fail<MemberResponse>("VALIDATION_ERROR", personError, StatusCodes.Status400BadRequest);
        }

        if (!string.IsNullOrWhiteSpace(request.FullName))
        {
            profile.User.FullName = request.FullName.Trim();
        }

        if (request.Phone is not null)
        {
            var phone = NormalizePhone(request.Phone);

            if (phone is not null && await _dbContext.Users.AnyAsync(
                    other => other.Phone == phone && other.Id != profile.UserId && !other.IsDeleted, cancellationToken))
            {
                return Fail<MemberResponse>("DUPLICATE", "So dien thoai nay da duoc su dung.", StatusCodes.Status409Conflict);
            }

            profile.User.Phone = phone;
        }

        if (request.DateOfBirth is not null)
        {
            profile.DateOfBirth = request.DateOfBirth;
        }

        if (request.Gender is not null)
        {
            profile.Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim();
        }

        if (request.Address is not null)
        {
            profile.Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim();
        }

        if (request.EmergencyContact is not null)
        {
            profile.EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim();
        }

        var now = DateTime.UtcNow;
        profile.UpdatedAt = now;
        profile.User.UpdatedAt = now;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return ServiceResult<MemberResponse>.Success(ToResponse(profile));
    }

    // FR-MEM-04 / DATA-01: soft-delete.
    public async Task<ServiceResult<object>> DeleteAsync(long id, CancellationToken cancellationToken)
    {
        var profile = await FindAsync(id, cancellationToken);

        if (profile is null)
        {
            return Fail<object>("NOT_FOUND", "Khong tim thay hoi vien.", StatusCodes.Status404NotFound);
        }

        profile.IsDeleted = true;
        profile.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("DELETE_MEMBER", "MemberProfile", profile.Id, null, cancellationToken);

        return ServiceResult<object>.Success(new { });
    }

    private Task<MemberProfile?> FindAsync(long id, CancellationToken cancellationToken)
    {
        return _dbContext.MemberProfiles
            .Include(profile => profile.User)
            .FirstOrDefaultAsync(profile => profile.Id == id && !profile.IsDeleted && !profile.User.IsDeleted, cancellationToken);
    }

    private Task<long> FindCurrentProfileIdAsync(long userId, CancellationToken cancellationToken)
    {
        return _dbContext.MemberProfiles
            .Where(profile => profile.UserId == userId && !profile.IsDeleted && !profile.User.IsDeleted)
            .Select(profile => profile.Id)
            .FirstOrDefaultAsync(cancellationToken);
    }

    // Admin/Staff: moi ho so. Member: chi cua minh (ownership). PT: can spec 005 (assignment) -> tam 403.
    private static bool CanAccess(ClaimsPrincipal principal, MemberProfile profile)
    {
        if (principal.IsInRole(RoleNames.Admin) || principal.IsInRole(RoleNames.Staff))
        {
            return true;
        }

        if (principal.IsInRole(RoleNames.Member))
        {
            return GetActorId(principal) == profile.UserId;
        }

        return false;
    }

    private async Task<Role> GetRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        var role = await _dbContext.Roles.FirstOrDefaultAsync(item => item.Name == roleName, cancellationToken);

        if (role is not null)
        {
            return role;
        }

        role = new Role { Name = roleName, Description = $"{roleName} role" };
        _dbContext.Roles.Add(role);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return role;
    }

    private static MemberProfile BuildProfile(CreateMemberRequest request)
    {
        return new MemberProfile
        {
            DateOfBirth = request.DateOfBirth,
            Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim(),
            Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim(),
            EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim(),
            JoinedAt = DateTime.UtcNow
        };
    }

    private static MemberResponse ToResponse(MemberProfile profile)
    {
        return new MemberResponse(
            profile.Id,
            profile.UserId,
            $"MEM-{profile.Id:D6}",
            profile.User.Email,
            profile.User.FullName,
            profile.User.AvatarUrl,
            profile.User.Phone,
            profile.DateOfBirth,
            profile.Gender,
            profile.Address,
            profile.EmergencyContact,
            profile.JoinedAt,
            profile.User.Status,
            profile.CreatedAt);
    }

    private static long? GetActorId(ClaimsPrincipal principal)
    {
        var value = principal.FindFirstValue(ClaimTypes.NameIdentifier) ??
            principal.FindFirstValue(JwtRegisteredClaimNames.Sub);

        return long.TryParse(value, out var userId) ? userId : null;
    }

    private static bool IsMemberProfileUserUniqueViolation(DbUpdateException exception)
    {
        return exception.InnerException is SqlException { Number: 2601 or 2627 } sqlException &&
            sqlException.Message.Contains("IX_member_profiles_UserId", StringComparison.OrdinalIgnoreCase);
    }

    private static string GenerateTemporaryPassword()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(9));
    }

    private static bool IsValidEmail(string email)
    {
        var at = email.IndexOf('@');
        return at > 0 && at < email.Length - 1;
    }

    private static string NormalizeEmail(string? email)
    {
        return email?.Trim().ToLowerInvariant() ?? string.Empty;
    }

    private static string? NormalizePhone(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone) ? null : phone.Trim();
    }

    private static ServiceResult<T> Fail<T>(string code, string message, int statusCode)
    {
        return ServiceResult<T>.Failure(code, message, statusCode);
    }
}
