namespace GymMaster.API.DTOs;

// Spec 002 — Member profile (FR-MEM-01..05)

public sealed record CreateMemberRequest(
    string FullName,
    string Email,
    string? Phone,
    string? Password,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact);

public sealed record UpdateMemberRequest(
    string? FullName,
    string? Phone,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact);

public sealed record MemberResponse(
    long Id,
    long UserId,
    string MemberCode,
    string Email,
    string FullName,
    string? Phone,
    DateTime? DateOfBirth,
    string? Gender,
    string? Address,
    string? EmergencyContact,
    DateTime JoinedAt,
    string Status,
    DateTime CreatedAt);

public sealed record CreateMemberResponse(
    MemberResponse Member,
    string? InitialPassword,
    bool PasswordAutoGenerated,
    bool LinkedToExistingAccount);

public sealed record Member360Response(
    Member360MemberResponse Member,
    Member360MembershipResponse? CurrentMembership,
    Member360AssignedPtResponse? AssignedPT,
    IReadOnlyList<Member360CheckInResponse> RecentCheckIns);

public sealed record Member360MemberResponse(
    long Id,
    string MemberCode,
    string FullName,
    string Email,
    string? Phone,
    string Status);

public sealed record Member360MembershipResponse(
    long Id,
    string PackageName,
    DateOnly StartDate,
    DateOnly EndDate,
    string Status,
    string PaymentStatus);

public sealed record Member360AssignedPtResponse(
    long Id,
    string FullName,
    string? Specialty,
    DateTime AssignedAt);

public sealed record Member360CheckInResponse(
    long Id,
    DateTime CheckInAt);
