namespace GymMaster.API.DTOs;

// Spec 002 — Trainer profile (FR-PT-PROF-01)

// Tao PT mot buoc: tao tai khoan (role pt) + ho so nghe trong 1 lan.
public sealed record CreateTrainerRequest(
    string? FullName,
    string? Email,
    string? Phone,
    string? Password,
    string? Specialty,
    string? Bio,
    string? Gender,
    DateTime? DateOfBirth,
    int? YearsOfExperience,
    string? Address = null,
    string? EmergencyContact = null);

public sealed record CreateTrainerResponse(
    TrainerResponse Trainer,
    string? InitialPassword,
    bool PasswordAutoGenerated);

public sealed record UpdateTrainerRequest(
    string? Specialty,
    string? Bio,
    string? Gender,
    DateTime? DateOfBirth,
    int? YearsOfExperience,
    string? Address = null,
    string? EmergencyContact = null);

public sealed record TrainerResponse(
    long Id,
    long UserId,
    string Email,
    string FullName,
    string Status,
    string? Specialty,
    string? Bio,
    string? Gender,
    DateTime? DateOfBirth,
    string? Address,
    string? EmergencyContact,
    int? YearsOfExperience,
    DateTime CreatedAt);
