namespace GymMaster.API.DTOs;

// Spec 002 — User Management (FR-USR, FR-MEM)

public sealed record CreateUserRequest(
    string FullName,
    string Email,
    string? Phone,
    string Role,
    string? Password);

public sealed record UpdateUserRequest(
    string? FullName,
    string? Phone,
    string? Status,
    string? Role);

public sealed record AdminUserResponse(
    long Id,
    string Email,
    string FullName,
    string? Phone,
    string Role,
    string Status,
    DateTime? LastLoginAt,
    DateTime CreatedAt);

public sealed record CreateUserResponse(
    AdminUserResponse User,
    string InitialPassword,
    bool PasswordAutoGenerated);

public sealed record PagedResult<T>(
    IReadOnlyList<T> Items,
    int Page,
    int PageSize,
    int TotalItems,
    int TotalPages);
