namespace GymMaster.API.DTOs;

// Spec 002 — User Management (FR-USR, FR-MEM)

public sealed record CreateUserRequest(
    string FullName,
    string Email,
    string? Phone,
    string Role,
    string? Password);

public sealed record UpdateUserRequest(
    string? FullName,
    string? Phone,
    string? Status,
    string? Role);

public sealed record AdminUserResponse(
    long UserId,
    string Email,
    string FullName,
    string? Phone,
    string Role,
    string Status,
    DateTime? LastLoginAt,
    DateTime CreatedAt);

// Flat response matching FE ManagedUser shape (includes password fields for POST /users)
public sealed record CreateUserResponse(
    long UserId,
    string Email,
    string FullName,
    string? Phone,
    string Role,
    string Status,
    string? InitialPassword,
    bool PasswordAutoGenerated);

public sealed record UpdateUserStatusRequest(string Status);

public sealed record ResetUserPasswordResponse(long UserId, string TemporaryPassword);

public sealed record PagedResult<T>(
    IReadOnlyList<T> Items,
    int Page,
    int PageSize,
    int Total,
    int TotalPages);
