using System.Security.Cryptography;
using GymMaster.API.Data;
using GymMaster.API.Entities;
using Microsoft.EntityFrameworkCore;
using GymMaster.API.Common;
using GymMaster.API.Features.Dashboard;

namespace GymMaster.API.Features.Users;
public sealed class UserService : IUserService
{
    private const int DefaultPageSize = 20;
    private const int MaxPageSize = 100;

    private readonly GymMasterDbContext _dbContext;
    private readonly IAuditService _auditService;

    public UserService(GymMasterDbContext dbContext, IAuditService auditService)
    {
        _dbContext = dbContext;
        _auditService = auditService;
    }

    // FR-USR-01: Admin tao tai khoan voi role chi dinh, trang thai Active.
    public async Task<ServiceResult<CreateUserResponse>> CreateAsync(
        CreateUserRequest request,
        CancellationToken cancellationToken)
    {
        var email = NormalizeEmail(request.Email);
        var phone = NormalizePhone(request.Phone);
        var role = NormalizeRole(request.Role);

        if (string.IsNullOrWhiteSpace(request.FullName) || string.IsNullOrWhiteSpace(email))
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Vui long nhap ho ten va email.",
                StatusCodes.Status400BadRequest);
        }

        if (!IsValidEmail(email))
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Email khong hop le.",
                StatusCodes.Status400BadRequest);
        }

        if (role is null)
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Role khong hop le (admin/staff/pt/member).",
                StatusCodes.Status400BadRequest);
        }

        // Admin co the tu nhap mat khau; de trong -> he thong tu sinh mat khau tam.
        if (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 6)
        {
            return Fail<CreateUserResponse>(
                "VALIDATION_ERROR",
                "Mat khau phai co it nhat 6 ky tu.",
                StatusCodes.Status400BadRequest);
        }

        var personError = PersonValidation.Validate(
            fullName: request.FullName,
            phone: request.Phone,
            dateOfBirth: request.DateOfBirth,
            gender: request.Gender,
            address: request.Address,
            emergencyContact: request.EmergencyContact);
        if (personError is not null)
        {
            return Fail<CreateUserResponse>("VALIDATION_ERROR", personError, StatusCodes.Status400BadRequest);
        }

        // FR-USR-02: email/phone da ton tai -> 409.
        if (await _dbContext.Users.AnyAsync(user => user.Email == email && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateUserResponse>(
                "DUPLICATE",
                "Email nay da duoc su dung.",
                StatusCodes.Status409Conflict);
        }

        if (phone is not null &&
            await _dbContext.Users.AnyAsync(user => user.Phone == phone && !user.IsDeleted, cancellationToken))
        {
            return Fail<CreateUserResponse>(
                "DUPLICATE",
                "So dien thoai nay da duoc su dung.",
                StatusCodes.Status409Conflict);
        }

        var roleEntity = await GetRoleAsync(role, cancellationToken);
        var autoGenerated = string.IsNullOrWhiteSpace(request.Password);
        var password = autoGenerated ? GenerateTemporaryPassword() : request.Password!;

        var user = new User
        {
            Email = email,
            Phone = phone,
            FullName = request.FullName.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(password, 12),
            Status = UserStatuses.Active
        };

        user.UserRoles.Add(new UserRole { User = user, Role = roleEntity });
        _dbContext.Users.Add(user);

        // Staff/admin: ghi luon thong tin ca nhan vao staff_profiles neu admin da nhap.
        var hasPersonalFields = request.DateOfBirth is not null ||
            request.Gender is not null ||
            request.Address is not null ||
            request.EmergencyContact is not null;
        if (hasPersonalFields && role is RoleNames.Admin or RoleNames.Staff)
        {
            _dbContext.StaffProfiles.Add(new StaffProfile
            {
                User = user,
                DateOfBirth = request.DateOfBirth,
                Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim(),
                Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim(),
                EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact)
                    ? null
                    : request.EmergencyContact.Trim()
            });
        }

        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("CREATE_USER", "User", user.Id, new { role }, cancellationToken);

        return ServiceResult<CreateUserResponse>.Success(
            ToCreateResponse(user, password, autoGenerated),
            StatusCodes.Status201Created);
    }

    // FR-MEM-02: tim kiem theo ten/email/SDT (khong phan biet hoa thuong) + phan trang.
    public async Task<ServiceResult<PagedResult<AdminUserResponse>>> ListAsync(
        string? query,
        string? role,
        int page,
        int pageSize,
        CancellationToken cancellationToken)
    {
        page = page < 1 ? 1 : page;
        pageSize = pageSize is < 1 or > MaxPageSize ? DefaultPageSize : pageSize;

        var users = _dbContext.Users
            .Include(user => user.UserRoles)
            .ThenInclude(userRole => userRole.Role)
            .Where(user => !user.IsDeleted);

        if (!string.IsNullOrWhiteSpace(query))
        {
            var keyword = query.Trim();
            users = users.Where(user =>
                user.FullName.Contains(keyword) ||
                user.Email.Contains(keyword) ||
                (user.Phone != null && user.Phone.Contains(keyword)));
        }

        var roleFilter = NormalizeRole(role);
        if (roleFilter is not null)
        {
            users = users.Where(user => user.UserRoles.Any(userRole => userRole.Role.Name == roleFilter));
        }

        var total = await users.CountAsync(cancellationToken);
        var items = await users
            .OrderByDescending(user => user.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var totalPages = (int)Math.Ceiling(total / (double)pageSize);
        var profileByUserId = await GetStaffProfileMapAsync(items, cancellationToken);
        var result = new PagedResult<AdminUserResponse>(
            items.Select(user => ToResponse(user, profileByUserId)).ToList(),
            page,
            pageSize,
            total,
            totalPages);

        return ServiceResult<PagedResult<AdminUserResponse>>.Success(result);
    }

    public async Task<ServiceResult<AdminUserResponse>> GetByIdAsync(
        long id,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        return user is null
            ? Fail<AdminUserResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound)
            : ServiceResult<AdminUserResponse>.Success(
                ToResponse(user, await GetStaffProfileAsync(user.Id, cancellationToken)));
    }

    // FR-MEM-03: validate va luu, cap nhat UpdatedAt.
    public async Task<ServiceResult<AdminUserResponse>> UpdateAsync(
        long id,
        UpdateUserRequest request,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<AdminUserResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        var personError = PersonValidation.Validate(
            fullName: request.FullName,
            phone: request.Phone,
            dateOfBirth: request.DateOfBirth,
            gender: request.Gender,
            address: request.Address,
            emergencyContact: request.EmergencyContact);
        if (personError is not null)
        {
            return Fail<AdminUserResponse>("VALIDATION_ERROR", personError, StatusCodes.Status400BadRequest);
        }

        if (!string.IsNullOrWhiteSpace(request.FullName))
        {
            user.FullName = request.FullName.Trim();
        }

        if (request.Phone is not null)
        {
            var phone = NormalizePhone(request.Phone);

            if (phone is not null && await _dbContext.Users.AnyAsync(
                    other => other.Phone == phone && other.Id != id && !other.IsDeleted, cancellationToken))
            {
                return Fail<AdminUserResponse>(
                    "DUPLICATE",
                    "So dien thoai nay da duoc su dung.",
                    StatusCodes.Status409Conflict);
            }

            user.Phone = phone;
        }

        if (!string.IsNullOrWhiteSpace(request.Status))
        {
            var status = request.Status.Trim().ToLowerInvariant();

            if (status != UserStatuses.Active && status != UserStatuses.Locked)
            {
                return Fail<AdminUserResponse>(
                    "VALIDATION_ERROR",
                    "Status khong hop le (active/locked).",
                    StatusCodes.Status400BadRequest);
            }

            user.Status = status;
        }

        if (!string.IsNullOrWhiteSpace(request.Role))
        {
            var role = NormalizeRole(request.Role);

            if (role is null)
            {
                return Fail<AdminUserResponse>(
                    "VALIDATION_ERROR",
                    "Role khong hop le (admin/staff/pt/member).",
                    StatusCodes.Status400BadRequest);
            }

            var currentRole = user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member;
            if (role != currentRole)
            {
                return Fail<AdminUserResponse>(
                    "ROLE_TRANSITION_NOT_ALLOWED",
                    "Role duoc gan khi tao tai khoan va khong the thay doi. Muon doi vai tro: tao tai khoan moi o man tuong ung va khoa/xoa tai khoan cu.",
                    StatusCodes.Status422UnprocessableEntity);
            }
        }

        StaffProfile? staffProfile = null;
        if (HasPersonalProfileFields(request))
        {
            var currentRole = user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member;
            if (currentRole is not (RoleNames.Admin or RoleNames.Staff))
            {
                return Fail<AdminUserResponse>(
                    "VALIDATION_ERROR",
                    "Ho so ca nhan cua hoi vien/PT duoc quan ly o man tuong ung.",
                    StatusCodes.Status422UnprocessableEntity);
            }

            staffProfile = await GetOrCreateStaffProfileAsync(user, cancellationToken);
            ApplyPersonalProfile(staffProfile, request);
        }

        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_USER", "User", user.Id, null, cancellationToken);

        return ServiceResult<AdminUserResponse>.Success(
            ToResponse(user, staffProfile ?? await GetStaffProfileAsync(user.Id, cancellationToken)));
    }

    // Cap nhat status Active/Locked cho user (PATCH /users/{id}/status).
    public async Task<ServiceResult<AdminUserResponse>> UpdateStatusAsync(
        long id,
        string status,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<AdminUserResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        var normalizedStatus = status.Trim().ToLowerInvariant();

        if (normalizedStatus != UserStatuses.Active && normalizedStatus != UserStatuses.Locked)
        {
            return Fail<AdminUserResponse>(
                "VALIDATION_ERROR",
                "Status khong hop le (active/locked).",
                StatusCodes.Status400BadRequest);
        }

        user.Status = normalizedStatus;
        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("UPDATE_USER_STATUS", "User", user.Id, new { status = normalizedStatus }, cancellationToken);

        return ServiceResult<AdminUserResponse>.Success(
            ToResponse(user, await GetStaffProfileAsync(user.Id, cancellationToken)));
    }

    // Reset mat khau tam cho user (POST /users/{id}/reset-password).
    public async Task<ServiceResult<ResetUserPasswordResponse>> ResetPasswordAsync(
        long id,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<ResetUserPasswordResponse>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        var tempPassword = GenerateTemporaryPassword();
        user.PasswordHash = BCrypt.Net.BCrypt.HashPassword(tempPassword, 12);
        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("RESET_PASSWORD", "User", user.Id, null, cancellationToken);

        return ServiceResult<ResetUserPasswordResponse>.Success(
            new ResetUserPasswordResponse(user.Id, tempPassword));
    }

    // FR-MEM-04 / DATA-01: soft-delete, KHONG xoa cung.
    public async Task<ServiceResult<object>> DeleteAsync(
        long id,
        CancellationToken cancellationToken)
    {
        var user = await FindAsync(id, cancellationToken);

        if (user is null)
        {
            return Fail<object>("NOT_FOUND", "Khong tim thay nguoi dung.", StatusCodes.Status404NotFound);
        }

        user.IsDeleted = true;
        user.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync("DELETE_USER", "User", user.Id, null, cancellationToken);

        return ServiceResult<object>.Success(new { });
    }

    private Task<User?> FindAsync(long id, CancellationToken cancellationToken)
    {
        return _dbContext.Users
            .Include(user => user.UserRoles)
            .ThenInclude(userRole => userRole.Role)
            .FirstOrDefaultAsync(user => user.Id == id && !user.IsDeleted, cancellationToken);
    }

    private async Task<Role> GetRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        var role = await _dbContext.Roles.FirstOrDefaultAsync(item => item.Name == roleName, cancellationToken);

        if (role is not null)
        {
            return role;
        }

        role = new Role { Name = roleName, Description = $"{roleName} role" };
        _dbContext.Roles.Add(role);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return role;
    }

    private async Task<Dictionary<long, StaffProfile>> GetStaffProfileMapAsync(
        IReadOnlyCollection<User> users,
        CancellationToken cancellationToken)
    {
        var userIds = users
            .Where(user => (user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member)
                is RoleNames.Admin or RoleNames.Staff)
            .Select(user => user.Id)
            .ToArray();

        return userIds.Length == 0
            ? new Dictionary<long, StaffProfile>()
            : await _dbContext.StaffProfiles
                .Where(profile => userIds.Contains(profile.UserId) && !profile.IsDeleted)
                .ToDictionaryAsync(profile => profile.UserId, cancellationToken);
    }

    private async Task<StaffProfile?> GetStaffProfileAsync(long userId, CancellationToken cancellationToken)
    {
        return await _dbContext.StaffProfiles
            .FirstOrDefaultAsync(profile => profile.UserId == userId && !profile.IsDeleted, cancellationToken);
    }

    private async Task<StaffProfile> GetOrCreateStaffProfileAsync(User user, CancellationToken cancellationToken)
    {
        var profile = await GetStaffProfileAsync(user.Id, cancellationToken);
        if (profile is not null)
        {
            return profile;
        }

        profile = new StaffProfile
        {
            UserId = user.Id,
            User = user
        };

        _dbContext.StaffProfiles.Add(profile);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return profile;
    }

    private static bool HasPersonalProfileFields(UpdateUserRequest request)
    {
        return request.DateOfBirth is not null ||
            request.Gender is not null ||
            request.Address is not null ||
            request.EmergencyContact is not null;
    }

    private static void ApplyPersonalProfile(StaffProfile profile, UpdateUserRequest request)
    {
        if (request.DateOfBirth is not null)
        {
            profile.DateOfBirth = request.DateOfBirth;
        }

        if (request.Gender is not null)
        {
            profile.Gender = string.IsNullOrWhiteSpace(request.Gender) ? null : request.Gender.Trim();
        }

        if (request.Address is not null)
        {
            profile.Address = string.IsNullOrWhiteSpace(request.Address) ? null : request.Address.Trim();
        }

        if (request.EmergencyContact is not null)
        {
            profile.EmergencyContact = string.IsNullOrWhiteSpace(request.EmergencyContact) ? null : request.EmergencyContact.Trim();
        }

        profile.UpdatedAt = DateTime.UtcNow;
    }

    private static AdminUserResponse ToResponse(User user, IReadOnlyDictionary<long, StaffProfile> profileByUserId)
    {
        profileByUserId.TryGetValue(user.Id, out var profile);
        return ToResponse(user, profile);
    }

    private static AdminUserResponse ToResponse(User user, StaffProfile? profile = null)
    {
        var role = user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member;
        var visibleProfile = role is RoleNames.Admin or RoleNames.Staff ? profile : null;

        return new AdminUserResponse(
            user.Id,
            user.Email,
            user.FullName,
            user.Phone,
            role,
            user.Status,
            user.LastLoginAt,
            user.CreatedAt,
            visibleProfile?.DateOfBirth,
            visibleProfile?.Gender,
            visibleProfile?.Address,
            visibleProfile?.EmergencyContact);
    }

    private static CreateUserResponse ToCreateResponse(User user, string password, bool autoGenerated)
    {
        return new CreateUserResponse(
            user.Id,
            user.Email,
            user.FullName,
            user.Phone,
            user.UserRoles.Select(userRole => userRole.Role.Name).FirstOrDefault() ?? RoleNames.Member,
            user.Status,
            password,
            autoGenerated);
    }

    private static string GenerateTemporaryPassword()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(9));
    }

    private static bool IsValidEmail(string email)
    {
        var at = email.IndexOf('@');
        return at > 0 && at < email.Length - 1;
    }

    private static string NormalizeEmail(string? email)
    {
        return email?.Trim().ToLowerInvariant() ?? string.Empty;
    }

    private static string? NormalizePhone(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone) ? null : phone.Trim();
    }

    private static string? NormalizeRole(string? role)
    {
        if (string.IsNullOrWhiteSpace(role))
        {
            return null;
        }

        var normalized = role.Trim().ToLowerInvariant();
        return RoleNames.All.Contains(normalized) ? normalized : null;
    }

    private static ServiceResult<T> Fail<T>(string code, string message, int statusCode)
    {
        return ServiceResult<T>.Failure(code, message, statusCode);
    }
}
